### ISSUE TITLE
0101-feel-constants.dmn '+' not allowed for numeric literal according to grammar rules

### ISSUE THREAD

**Issue by arthware** [dmn-tck/tck#11]
I am currently testing the TCK for ACTICO GmbH against our DMN runtime currently under development. 
We plan to integrate the TCK tests as part of our continous builds.

One test, that is failing is _0101-feel-constants.dmn_ for _compliance-level-2_
Our grammar does not allow the '+' character to express positive numbers. 

` <decision name="Decision3" id="d_Decision3">
      <variable name="Decision3" typeRef="feel:number"/>
        <literalExpression>
            <text>+.872</text>
        </literalExpression>
</decision>`

According to the spec, this test does not seem to be compliant: 
_chapter 10.3.1.2, page 108, grammar rule 37: numeric literal = [ "-" ] , ( digits , [ ".", digits ] | ".", digits ) ;_

Only '-' is allowed to express negative numbers. Did we miss something here? 

Thanks for your feedback and good to be on board with ACTICO.

**Comment by arthware** [comment]
_0101-feel-constants.dmn_ has been added just recently to the testsuite:

https://github.com/dmn-tck/tck/commit/7849284ac243436a83c5e7f887a697df0468f5a5#diff-51a9a8a87a5878f9aec47275a779577b

**Comment by etirelli** [comment]
PR was merged.
