### ISSUE TITLE
testCases.xsd does not support empty context (without name)

### ISSUE THREAD

**Issue by DanielThanner** [dmn-tck/tck#128]
What is the valid way to define an expected test result for an empty context? The FEEL Expression "{}" is an empty context. To define the test result for this case I guess the nillable attribute was added. But the name attribute is required. Therefore a dummy name must be used.

    <testCase id="example123">
        <resultNode name="feel-ctx-abc" type="decision">
            <expected>
                <component xsi:nil="true" name="dummyName" />
             </expected>
        </resultNode>
    </testCase>

Should we remove the required-flag for the name attribute, or is there another way to define an expected result value for an empty context?

**Comment by etirelli** [comment]
That's a good question. 

We represent an empty list as:
```
<expected>
    <list/>
</expected>
```

Maybe as you said removing the required-flag from the name attribute would be enough?
```
<expected>
    <component/>
</expected>
```

I think xsi:nil="true" would mean the context itself would be null, not empty, so I would prefer to simply keep an empty <component/> tag there.

**Comment by agilepro** [comment]
I think that Daniel said he would make pull request to make that element optional.  Please move forward on this if possible.

**Comment by DanielThanner** [comment]
Created pull request #134

**Comment by agilepro** [comment]
Looks OK
