### ISSUE TITLE
What is the result of a filter that is not a boolean?

### ISSUE THREAD

**Issue by etirelli** [dmn-tck/tck#129]
The spec says, on page 113:
```
[1, 2, 3, 4][item > 2] = [3, 4]
[ {x:1, y:2}, {x:2, y:3} ][x=1] = {x:1, y:2}
```

And:

> The filter expression is evaluated for each item in list, and a list containing only items where the filter expression is true is returned.

Based on the above, what is the result when a filter evaluates to a non-boolean value and/or to an error?

E.g.:

```
{ 
    a list : [ { a : false, b : 2 }, { a : null, b : 3 }, { b : 4 }, { a : true, b : 5 } ],
    r : a list[a] 
}.r
```

Our understanding is that this should:

- when evaluated for the first element `{ a : false, b : 2 }`, `a` is a `false` boolean-literal, hence not selected,
- when evaluated for the second element `{ a : null, b : 3 }`, `a` is the `null` literal, hence not selected
- when evaluated for the third element `{ b : 4 }`, there is no `a`, the filter would be an error, hence return null, hence not selected
- when evaluated for the fourth element `{ a : true, b : 5 }`, `a` is the `true` boolean-literal, so it will be selected

The result of the expression then would be:
```
[ { a : true, b : 5 } ]
```

**Comment by DanielThanner** [comment]
The spec additionally says in table 54 on page 127 (row 3, column 4): "e1 is a list and type(FEEL(e2, s')) is boolean"

Conclusion: If e2 is not a boolean type (true or false) the expression is not applicable. 

I think the complete result of the filter expression should be null.

**Comment by etirelli** [comment]
@DanielThanner the main reason for my question is because of the "if" statement that says (page 120):

> A conditional if a then b else c is equal to b if a is true, and equal to c otherwise.

And Gary confirmed that:

```if "foo" then 1 else 2 = 2```

Page 113, on filters, says:

> The filter expression is evaluated for each item in list, and a list containing only items where the filter expression is true is returned.

To be honest, my current implementation returns null, as you mentioned. But the above wording makes me think we might be wrong.

**Comment by DanielThanner** [comment]
May be we should create a OMG ticket to clarify that issue for DMN 1.2.

**Comment by etirelli** [comment]
I sent the question to Gary just in case. Once we hear from him we can open a ticket if necessary.

**Comment by garyhallmark** [comment]
I think its worth an issue for the RTF. Table 59 (after ballot 13): Semantics of lists is unclear. The table should be captioned "Semantics of filters". It is unclear how to interpret Applicability. Must the expression be true for every list item? How is applicability related to the domain of the inputs to the filter? If an input is out of its specified domain, the the result must be null. But its not clear here...

**Comment by opatrascoiu** [comment]
FEEL has a 3-value logic. Hence returning only those elements for which the filter returns `true` makes sense as `true != null` .

I believe SQL takes the same approach. Same thing happens in Java if the filter returns `null `and is compared against `Boolean.TRUE`.

**Comment by agilepro** [comment]
RTF discussed.  Last comment above is correct.  Closing.
