### ISSUE TITLE
Should encapsulated decisions of a decision service include output decisions?

### ISSUE THREAD

**Issue by DanielThanner** [dmn-tck/tck#132]
For us it is unclear what decisions should be stored in the DMN model as encapsulated decisions. Must the output decisions also be included in the list of encapsulated decisions (as stated on page 25, 26)? Or does the list of encapsulated decisions only hold the decisions contained in the lower compartment of a decision service (as mentioned on 56 since encapsulatedDecisions seems to be optional)?

**Comment by opatrascoiu** [comment]
I believe the list of encapsulated decisions does not contain the output decisions.

Have a look at Figure 11 (page 26) from DMN 1.1.

Output Decisions: `Decision 1`
Encapsulated Decisions: `Decision 2`
Input Data: `Input data 1`, `Input data 2`

Hope this helps.

**Comment by agilepro** [comment]
Is that sufficient?  Should we close this?

**Comment by DanielThanner** [comment]
@opatrascoiu I think you mean Figure 10 on page 26. In Figure 11 the decision service has only a single decision.

The description of Figure 10 is on page 25, last paragraph: "The encapsulated decisions are therefore {Decision1, Decision2}."

We think that the description of Figure 10 is wrong. As you mentioned, the encapsulated decisions should only be Decision2.

**Comment by DanielThanner** [comment]
I raised an issue in OMG Jira. It is currently in their INBOX.

**Comment by DanielThanner** [comment]
https://issues.omg.org/browse/DMN12-271

**Comment by DanielThanner** [comment]
Proposal to change DMN specification:

Change the following sentence in DMN 1.1, Table 20, Row encapsulatedDecisions: 
"If present, this attribute lists the instances of Decision to be
encapsulated in this DecisionService"

to the following sentence: 
"If present, this attribute lists the instances of Decision to be
encapsulated in this DecisionService. **This list does not include any output decisions.**"

**Comment by DanielThanner** [comment]
Proposal added to OMG ticket. This issue can be closed.
