### ISSUE TITLE
Minimal set of automatically generated test cases

### ISSUE THREAD

**Issue by bzinchenko** [dmn-tck/tck#152]
We generated a set of test cases for all models in current DMN TCK. Please see appended. If somebody with ready and configured runner might run them for consistency, it might be curious. Of course, tests are very formal and schematic. But still, it is interesting, if we comply to semantics. Thank you.

[TestCases_AutoGenerated_2018_05_10.zip](https://github.com/dmn-tck/tck/files/1991949/TestCases_AutoGenerated_2018_05_10.zip)

**Comment by agilepro** [comment]
This is not really helpful until you have real tests that actually run, and we DO require all test submissions to be fully running at the time of submission.  I will close this.  When you have running tests, submit them as a pull request.
