### ISSUE TITLE
What is the meaning of "Skipped?"

### ISSUE THREAD

**Issue by agilepro** [dmn-tck/tck#165]
We allow vendors to designate a result as "failed" or "skipped".  What is the difference?  

The question is one of credibility to the visitors of the results site.  If every vendor was to mark all failures as skipped, what does it mean.

For me personally: I felt that skipped was to be used to designate areas that the vendor does not implement, and has a reason to not implement.  For example: say that the spec had a feature for reading and writing Excel files, and vendor decides not to support that.  So ... they mark all the tests for Excel file as "skipped" to tell users that they simply decided not to implement that.  Is that what skipped means to others?

Since the tests are contributed, and because each implementation is different, the "skipped" setting is an escape valve to prevent one vendor from submitting a lot of tests just to make another vendor look bad.  The ability for a vendor to avoid certain categories of tests seems important. 

For this to work, I think some sort of explanation is needed.  That explanation needs to persuade the visitors that there is a good reason that they will not need the functionality represented by the tests.   There is no question that "skipped" means that the test does not function on that vendor.

One simple way to handle this is to expect that a vendor include these details on the overview sheet.  Is that sufficient?

Or, should we require that any skipped test be mentioned on a "black list" and that some form of explanation be given.  There IS a spot in the results to make this explanation.  Should we require that a skipped result have a comment?  Is that sufficient?  Is that necessary?

PLEASE COMMENT - I am putting this issue on the site because I want to get everyone's input.

**Comment by dgagne** [comment]
We should change the term "skip" for  "not implemented"
This way the semantic will be clear.

**Comment by DanielThanner** [comment]
"skipped" is currently used if the vendor doesn't support this feature. Therefore we should rename it to "not supported". "not implemented" would be also okay.

Additionally we can introduce a new category: "currently under development" or "available in future releases" This category can be used to signal that the vendor has planned to support this feature in the near future.

**Comment by etirelli** [comment]
I agree that we should re-vamp the statuses and I like the suggestions from @DanielThanner , except for the "available in future releases". Unfortunately, I am afraid that this would then become the new go to status and would just replace "skipped" for all tests not supported by a vendor.

I think the following list provides proper reflection of what the current status of each product is:

* unsupported
* unknown
* succeeded
* failed

**Comment by etirelli** [comment]
As discussed in the call:

* not submitted: the vendor did not submit a result for the test
* succeeded: the test runs successfully
* failed: the test fails on execution
* not supported: the test is not supported

**Comment by etirelli** [comment]
Submitted PR #165 to implement the change discussed here. Please note that at the moment I did not make any change to the way vendors report results, as it wasn't necessary. I just changed the way the website reported the results:

* succeeded
* failed
* not supported
* missing

For not supported tests, vendor will continue to report the status on the results file as "IGNORED", to avoid changing their runners and old reported files. On the website, these tests will show as "not supported".

Please review the PR and if approved we can close this ticket.

**Comment by agilepro** [comment]
PR has been merged that takes care of this.
