### ISSUE TITLE
TCK Observations / notes / questions

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#196]
All, maybe some stuff for discussion.  Below are my notes re the current TCK.  I mean no offence to anyone.  The effort so far has been amazing. Well done.  This is just a basic audit on what I have experienced and what my code coverage looks like.  My first read of the spec was maybe 5 weeks ago and thus far, I have developed in isolation.  So, I am a complete DMN newb and likely have it wrong.  I am happy to be corrected/slapped.  Apologies if this is covered elsewhere.

# TCK Notes / observations / issues

## Issues

* I tested a few DMNs against the schema and some failed - so I didn't test the rest.  Should it be a basic requirement of the test DMN that it passes schema validation?
* the grammar states that a 'function definition' is not part of a "textual expression".  Only a "boxed expression" may have a function definition.  A textual function can only 'invoke' functions, not define them.  Which make the tests and examples for the 'sort' function where a function is defined inline invalid.  ?  If it is not invalid then it must be legal to pass a function to (say) a BKM. Which sounds 'dangerous' as the BKM is no longer self-contained and means the BKM now has a dependency on something in (say) a decision. 
* some tests use the output of string() for their assertions.  The output of string() is not defined by the spec.
* 0003 has a typeRefs of 'tck:tEmploymentStatus' and 'tns:tLoan' but they are not actually defined.  There is a type 'tEmploymentStatus' and a 'tLoan' defined, but neither bound to the 'tck' namespace.  What is the policy?
* some tests have typeRefs that are non-existent (without or without namespace).  What is the policy?

### Large-ish

* no DecisionService coverage
* no equivalence coverage
* no conformance coverage
* no import coverage
* very little add/subtract coverage beyond numbers and strings 

### Basic FEEL tests:

some coverage - but mostly 'incidental' in nature.  Not specific tests.

Assert:

* which chars are whitespace
* which chars may be included in names
* inclusion of extra chars in names
* string escape chars 
* disambiguating names with spaces ()giving precedence to longest scope name) - wrap not longest scope name in ()
* truth table matrix for AND/OR/NULL
* type equality equivalence between types 
* type conformance
* 2.00 = 2
* 0 = -0
* ** is right associative (spec doesn't say it, but it is)
* multi-line expressions
* comments in expressions //-EOL and /* */
* var names with cr/lf in them
* order of precedence

### Boxed Expressions

* pretty sure there is no coverage for nested boxed expressions

#### Decision tables:

No coverage for:

* 'not' usage in unary tests (it is in a single test, but is incidental)
* input clause expressions that fail unary tests should result to null
* output entries that fail output clause unary tests should result to null
* P/O hitpolicy - null values in output values and how they affect priority sorting
* P/O hitpolicy - multi-column priority when some or all columns do not have unary tests
* P/O hitpolicy - how to handle failures in output clause unary tests
* 'any' hit policy - verify the multiple results are actually the same (using type equivalence)
* input/output clause unary tests with ranges - all tests seems to be on static strings
* open/closed start/end ranges (might be but I haven't seem then ..)
* defaultOutputEntry for multi column results
* return value when no results and no defaultOutputEntry (for each hitPolicy)
* return value for U hitPolicy when more than one result
* '?' value in scope for generalised cell expression  
* an input entry generalised expression returning a value, not a boolean

#### Boxed expr List:

* no coverage for list element that are 'expressions', test cover only string/numeric literals
* no coverage for list cells that are other boxed expressions

### Literal Expressions:

* no coverage for inline contexts like {foo: "bar"}, {foo bar: a + 1}, or {a: 1, : b: a + 1}
* no coverage for 'instance of'
* no coverage for array property access with negative indexes
* no coverage for array 'out of bounds'
* path accessor: when left evaluates to null
* path accessor: when left evaluates to neither a list nor a context
* path accessor: on qname-like nested contexts/lists
* negation: return null when negating a non-number
* no coverage for 'between'
* for/in: no coverage on ranges like 1..10, 5..x+10, -10..10  
* for/in: no coverage on reverse looping like 10..0, -10..-5  

### Function Definitions
* grammar rule 58 says that a function definition (say for a context), the type of a formal param can be specified after a ':' like 'function(a:string, b:xsd:dateAndTime)' or 'function(a:string, b:feel:date and time)'

### Built-in functions

* for/every  
- Should return true when list is empty
- no coverage for nested iteration contexts
- no 'true' test (all test assertions are 'false' )

* for/some:  
- Should return false when list is empty
- no coverage for nested iteration contexts
- no 'false' test (all test assertions are 'true' )

* number() - no coverage
* all() - no coverage
* any() - no coverage
* append() - no named params coverage, no type conformance assertion coverage
* concatenate() - no named params coverage, no type conformance assertion coverage, no singleton array coverage
* distinct values() - no 'equality' checking as per spec - with contexts and lists and range and functions etc.
* indexOf() - no 'null' param coverage, no 'equality' checking as per spec
* insert before() - no 'null' param coverage, no type conformance checking, no list bounds checking
* list contains() - no 'equality' checking as per spec, only 'false' is tested.  Maybe no named params test.
* max() - return null for empty list not covered, non-numbers not covered.  strings - dates, time, durations
* max() - return null for empty list not covered, non-numbers not covered.  strings - dates, time, durations
* mean() - return null for empty list not covered, what to do when list if non-numbers.
* median() - no coverage
* mode() - no coverage
* remove() - no null param coverage.  no list index bounds coverage, position == 0 not covered 
* reverse() - no null param coverage
* sort() - no null param coverage. refer in 'issues' section re embedded function defs in literal expressions.  Tests assume 'stable' sort but spec has no requirement for that.
* stddev() - no coverage.  spec example assumes 'sample' stddev algorithm, not 'population' algorithm, though it is not specified.
* sublist() - no null param coverage.  No coverage for leaving off optional 'length' param
* sum() - return null for empty list not covered, non-numbers not covered
* union() - no type conformance checking. 
* abs() - no coverage
* ceiling() - no coverage for non-number (inc null).
* even() - no coverage. 
* floor() - no coverage for non-number (inc null)
* log() - no coverage
* modulo() - no coverage
* exp() - no coverage
* odd() - no coverage
* sqrt() - no coverage
* endsWith() - no coverage for non-string (inc null)
* lowercase() - no coverage for non-string (inc null)
* matches() - no coverage for non-string params (inc null). no coverage for invalid regex.
* replace() - no coverage for non-string params (inc null). no coverage for invalid regex or invalid flags.
* split() - no coverage
* length() - no coverage for non-string params (inc null).
* substring() - no coverage for non-string params (inc null).
* substring after() - no coverage for non-string params (inc null).
* substring before() - no coverage for non-string params (inc null).
* uppercase() - no coverage for non-string params (inc null).

## Other:

* the word 'in' cannot appear in names for 'for .. in' statement. Should include in tests?

## Questions

* When a decision does not define a variable, were does the output go?  What *is* a decision without a variable?
* Are entries in context ordered to have peer-dependencies for later entries resolved by earlier entries?
* context 'get value' and 'get entries' are not in the built-in functions list - should they be implemented?  If should if 'key' of get value a string or an expression?  If an expression that makes pre-compilation an type-inference not possible.
* when a unary test within a unarys tests returns null how does this impact the overall result of the unary tests.  

## Notes

* testCases.xsd:  has a test type of 'bkm' but it is not used anywhere.
* testCases.xsd: what is the 'computed' result node?

**Comment by tarilabs** [comment]
> I tested a few DMNs against the schema and some failed 

Can you kindly list actually which ones, please?
As we have Travis CI performing schema check for all DMN models in the suite, and no error is currently reported as far as I know. Thanks.

**Comment by StrayAlien** [comment]
Hi tarilabs, a 5 year absence from the java ecosystem has my Java/xsd kung-foo a little rusty.  But both xmlspy and a small 'check a schema' app fail on '0003-iteration.dmn'.  The 'variable' element for the bkm "PMT2" is out of sequence.  It is the first I one checked at random.  Like I said, a bit out-of-practice on Java but I thought it worth noting - could be me and my setup.

Greg.

**Comment by tarilabs** [comment]
> EDIT: I should note I am using DMN12.xsd against the current dmn.

That is the problem. Currently TCK suite is based on DMNv1.1 and the migration work is currently in-progress on a PR branch here: https://github.com/dmn-tck/tck/pull/191

Can you kindly confirm there is NO schema validation using the correct XSD, meaning DMNv1.1 as embedded here: https://github.com/dmn-tck/tck/blob/master/TestCases/dmn.xsd
or available here: https://www.omg.org/spec/DMN/1.1
(is the same `dmn.xsd` file)

please?

**Comment by StrayAlien** [comment]
Thanks, (Matteo?),

That looks like it.  Using 1.1 passes.  Thanks.  

Greg.

**Comment by tarilabs** [comment]
> 0003 has a typeRefs of 'tck:tEmploymentStatus' and 'tns:tLoan' but they are not actually defined. There is a type 'tEmploymentStatus' and a 'tLoan' defined, but neither bound to the 'tck' namespace.

I cannot locate `tck:tEmploymentStatus` in any file of `TestCases/compliance-level-3/0003-iteration` directory.
![image](https://user-images.githubusercontent.com/1699252/48830944-0cb65580-ed76-11e8-9aab-aedfa4810b31.png)

Then to what concerning: `tns:tMonthlyPaymentList` and `tns:tLoan` etc. I will make example with `tns:tMonthlyPaymentList`:

This typeref:
![image](https://user-images.githubusercontent.com/1699252/48831148-83535300-ed76-11e8-9318-1e8fcbeaa497.png)

is using (DMNv1.1) prefix `tns:` which for this model is bound to:
![image](https://user-images.githubusercontent.com/1699252/48831198-a3831200-ed76-11e8-92a3-b8c3d00108ad.png)

which is the same as this model DMN's `namespace`.

This means it is indeed referencing the DMN ItemDefinition defined in _this_ model:
![image](https://user-images.githubusercontent.com/1699252/48831263-c1e90d80-ed76-11e8-807a-79c7b156ef4f.png)

Please notice because in this DMN XML file the default _XML_ namespace is bound to: 
![image](https://user-images.githubusercontent.com/1699252/48831432-1be9d300-ed77-11e8-89a3-e5f03fd5df21.png)
you MUST use the `tns:` prefix otherwise it would need to look-up ItemDefinition in the default namespace which would be the DMN-specification definition namespace, and not this model namespace.

Does this clarify, please?
 - Matteo

**Comment by StrayAlien** [comment]
Matteo, thank you very much.  Yes, that does clarify.  I am certainly going to owe you some beers after this I can tell.

The 0003 is my mistake.  tns:tLoan is in 0003 in *L3*, and tck:tEmploymentStatus is in 0003 in *L2*.  I got them 'together' in my notes.  But, many thanks.  

That also does clear some fog around how namespaces are used in DMN.  I had been looking and looking but missed the relationship between the definition 'namespace' attribute and another xmlns prefix value.

Thank you again.

May I ask what is the policy when a typeRef does not exist at all?   L3 test '0031-user-defined-functions' the typeRef 'ns1:tFnInvocationResult' is used twice.  The 'ns1' parts defined as per your explanation above, but the 'tFnInvocationResult' is not defined anywhere - namespace or not.

Greg.

**Comment by StrayAlien** [comment]
Hi Edson,

Thanks for the response, and the background.  Important stuff.

Re errors: Yes, I had noticed that.  In the absence of specific guidance of things like that then perhaps 'convention' plays a part.  As implementors, if we agree on a common way then almost as good.  Another example of this is the string() function and what it outputs.  Not in the spec, but likely worth establishing a convention for.  Perhaps a third test folder called 'conventions' that are tests for things outside the spec but a there in good faith to help with interoperability.

Re the audit: Thanks.  My intention here is not to drop work on everybody's lap! I'll be doing some of those in time (I still have some other things to get done - likely porting the prototype from Typescript to Java).  As I've not been involved as yet I didn't want to start with a bunch of PRs without first verifying that the work wasn't already underway, or I wasn't being stupid. I am happy to contribute - it is why I've been buggin' you all. :-)

To the specifics:

* Decision Service.  Cool.  Thanks.

* equivalence - 1.2 tables 47 and 48 "Equality and Inequality".  I believe wherever the '=' is used, FEEL is to perform a *deep* equality check, not a shallow check like a '==' in (say) Java. Lists and contexts are compared 'deeply'.  I believe this should be in effect for the '=' operator in FEEL but also for other stuff like list functions:
 
 these should all use deep equality and not '==' style checking:
"indexof" 
"contains
"distinct value"
"union"

Likely most Java implementors have used .equals() for same, but I was noting there is no coverage asserting deep equality, only shallow.

Re 'a = [a]'.  Thanks, I thought that was in!!  And yes, it creates nasty ambiguities.  But ... the *coercion* of singleton list to a value where a list is not expected is still in yes?  Like uppercase(["foo"]) should result in "FOO".

* Conformance

1.2 section "10.3.2.9.2 Type Conformance".  Types conform to each other (or not!).  I may be wrong but my take on it is this: If, say, an Invokable formal param is for type 'X' then I believe the spec says I should be to pass it 'X' or a conforming type as a param. For example, if it requires a context param type like context<age:number, name:string> and I wish to invoke it passing in a context param like {name: 'foo', age: 10, bar: 'bar'} then that is okay, but passing it {name: 'foo'} is not - it does not meet the type expectations of the Invokable param.

I had a feeling it may have also be required to keep typed lists homogeneous - and thus used in a few list operation like 'insert before' and so on to enforce type safety.  But as lists are immutable I think the emphasis for type checking is at the contractual level of invocation and return types - that is if (say) the formal params of an Invokable says it requires a list<string> then that needs to be checked.  Likewise, if the invokable variable type is a list<number> them the data going into that variable needs to be checked for type conformance. There is a test that verifies that a singleton list is unwrapped to conform to a variable type but nothing deeper there.

This is what I mean.  Hopefully that makes sense.

Re L1/l2 vs L3 'conformance'.  Agree.  I wouldn't be spending time on anything by L3. 

* Re import: great, coz I dont quite 'get' it all as yet. :-)

* Re the weekly call.  Thanks. Keith has added me to that.  I think it is at 3am on Saturday morning my time ..... <gulp>

Again, many thanks.

Greg.

PS.  I bought the book.  Well done to you both.  Thanks.

**Comment by etirelli** [comment]
Greg,

I think I understand now, you were looking at the DMN 1.2 spec. :)

* equivalence: ok, we need to improve on that area then

> Re 'a = [a]'
yes, what is defined in the 1.2 spec will be supported and needs to have tests added, but that is quite different from what was in 1.1, and so we avoided testing it in 1.1. We actually removed a couple tests we had for that when some vendors complained. 

> Type Conformance
this is all new to 1.2. We need to add tests for that once we move to DMN 1.2

> "I think it is at 3am on Saturday morning my time"
:) ouch, where are you based? Australia/New Zealand?

> PS. I bought the book. Well done to you both.
Thanks! :)

**Comment by etirelli** [comment]
> Is the embedding of a anon function definition (lambda?) 'inline' in a literal expressions one of those differences?

No, anonymous functions are supported and have not changed since 1.1. The only place they are used in the core API though is in the sort() function. It is possible for a user to assign a name to a function as part of a context and pass it around, the same way that you would do in a functional language. 

It is possible as well to pass a BKM name (that is a function after all) as the parameter for the sort() function. For instance, in this old example:

http://blog.athico.com/2017/01/dmn-runtime-example-with-drools.html

"passenger priority" is a BKM (i.e. a function) with a decision table that defines the relative priority between 2 passengers. The "Prioritized Waiting List" decision uses that to invoke the sort() function like:

sort( Waiting List, passenger priority )

We don't have many tests for inline functions because most vendors are still working on its support, and it is somewhat an edge feature. The idea is to add coverage over time.

>  parsing a sort() expression darn hard

It is not that hard, once you get the grammar in place.

> As I read it, the 1.2 spec grammar has it that a function definition is not in a textual expression, only a boxed expression

That is just the name of the grammar rule. FEEL supports any syntax that is parseable by its grammar.

> I learned a lot from it and my copy has notes in the margins re things I didn't quite get in the spec

Glad to hear. If you have specific questions feel free to send me an e-mail.

**Comment by StrayAlien** [comment]
Thanks Edson, I get the lamda, context function, BKM as function thing - no issues there - maybe apart creating stuff that is hard for people to follow.  sort() is easy to parse when things are 'knowable' I guess.  Rather than overload this thread, I'll start a new one.

**Comment by StrayAlien** [comment]
closing.  Still lots lots do, but this will be here in issue history.  I have started on some if the things noted here.
