### ISSUE TITLE
question: the 'non-compliant' folder

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#200]
Hi all,

We supposed to do anything with that folder?  Is it 'unofficial' TCK?

Greg.

**Comment by tarilabs** [comment]
Contains test which did not conform to the standard and need to be aligned to be included in the CL2 or CL3 folder, which are the only ones actually run. But most importantly contained test for which an issue was raised to the OMG RTF, hence pending or needed align with the result of said issues. If you have a chance to work on any of them, this community will definitely appreciate, won't be a trivial task tho :)
