### ISSUE TITLE
type coercion for decision func/BKM results breaks some TCK tests

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#205]
Hi all,

I was implementing (and writing some assertions) re the following:  

If a decision result does not match the type of the variable its value is being assigned to - say the variable type is "number" and the decision results in a string. Then the value, I feel, should be coerced to null.  It is not within the semantic domain of the variable and therefore becomes null.  

Same for BKM or other func invocation that has a typed result.  If the actual result type does not match the expected result type then it should be null-coerced.

I am happy to hear comments on this.

If I implement this then two existing TCK tests fail. `015(0012-list-functions-test-01)/0` and `015(0012-list-functions-test-01)/0` where the trailing /0 is the result node #.

The reason being is their vars are typed for a 'list of lists' but that is not what is produced.  The results are a list like ["a", "b", ["c", "d"]], which is a mixed list -  some primitive and a list.  

The fact that the tests break if I implement this says maybe nobody is doing it, or nobody is doing it the same way, or I have missed something ... 

So:  a) should we be null-coercing non-conforming values coming out of decision and BKM/funcs? I think yes as those values represent 'input' to those vars.  And b) what are people thoughts on this?   Should I amend these tests to fit that assertion?

(from spec)

> Inputs outside of their domain result in a null value, unless that input is a singleton list, whose single element belongs to the domain; in which case, the single element should be unwrapped and used instead of the list.

Comments welcome.

Greg.

**Comment by StrayAlien** [comment]
I think I understand this now.  When I add the null-coercion described above those tests fail type conformance checking because the singleton equality rule of `a = [a]` has been removed from DMN for 1.2.

The types in those tests conform if singleton equality is in place.  They do conform not when not in place.  My code is 1.2 and thus does not implement singleton equality.

Some more discussion here: https://github.com/dmn-tck/tck/pull/204#discussion_r241908520.

I'll amend the tests reflect the removal of singleton equality from the spec and the null-coercion above put in.  I'll add that to a PR.

@agilepro, as this is a change to (two) existing TCK tests we might need to communicate it around. 

Greg.

**Comment by etirelli** [comment]
@StrayAlien I agree with you that it makes sense to generate an error if a value outside of the domain is assigned to a variable, but the spec does not clearly define how this is done. Each vendor is basically free report the error in any way they wish, so this has been hard to standardize on the TCK.

Just to mention the example of Drools, we have a configuration flag that when enabled will verify that the value matches the type/domain of the variable and report error and return null. When disable, it ignores the variable type and uses it just as a "hint" of what the value should be, but much like dynamic languages (like JS) allow for the mutation of the type during runtime.

Without the spec being explicit about it, I don't think we can test it in the TCK, one way or another.

**Comment by StrayAlien** [comment]
Hi @etirelli , thanks for the reply.  Re the flag, I have a similar one - it makes sense. :-)

However,  I do think we can test this.  It not about the generating an error, it's about the null coercion.  I believe attempting to assign a value to a var, or return a result form an expression that is outside of it domain should make it null.   This is how built-in funcs operate, as well as values in DT cells and so on.  With built-in funcs, it does say, for example, the result is null - not err and stop execution. 

> When a built-in function encounters input that is outside its defined domain, the function SHOULD report or log diagnostic information if appropriate, and SHALL return null.

Many things in DMN can have a typeref.  A DT can.  If the DT returns a value that is outside that typeref domain, my feeling is the return value of the DT should be null - it that value it returns is outside the domain of the assigned var, then it should be null.  Same for other expressions - for example a literal expression can have a typeref.  If the return value of the expression does not conform to that type then it should be null.  Log an error yes, but it should be null.

To that end the current tests PR I have in has a number of assertions for same.  eg: a literal expression says it should return a string, but it actually returns a number.  The actual result is null.

So I think we can and should test for this.

Comments welcome.   

Greg.

**Comment by StrayAlien** [comment]
Hi @etirelli, thanks for response.

Just to confirm: I think you're saying you believe that any any out-of-domain assignment or param should stop model execution and cause an error?  I don't think the spec actually says that.

> When a built-in function encounters input that is outside its defined domain, the function SHOULD report or log diagnostic information if appropriate, and SHALL return null.

 The func shall return null.  Not 'execution shall stop and the result of the model evaluation result shall be null'.  

null-coercion like this is implicit in other parts of the spec. Namely in DTs when a cell value falls outside the input or output values domain - null coercion.  Log errors/info as you wish, but make it null - it is not an error.

My feeling is we should assert that, say, a literal expression that actually (at runtime) returns a number but has a string type in the definition is coerced to null because it doesn't stop execution.  For example, a value in a context with such an expression should get a null value and execution continues - not an error (whatever an 'error' actually is).  Yes - log stuff, but keep executing.

> Each vendor is basically free report the error in any way they wish, so this has been hard to standardize on the TCK.

I agree - this is hard, but I'm not actually referring to asserting on errors, more asserting on null-coercion behaviour when actual runtime type does not conform to defn domain type.  There are tests in my current PR to assert this.

Does that make and sense?

**Comment by opatrascoiu** [comment]
I think the spec should contain a section about type conversions. I was planning to submit a proposal for that in DMN 1.2, but I didn't have time. I managed though to add a section about type equivalence and conformance. Type conversions usually are built on top of those relations. I'll try to submit a proposal to clarify this.

**Comment by opatrascoiu** [comment]
Raised this issue https://issues.omg.org/browse/INBOX-809

**Comment by opatrascoiu** [comment]
Was moved to https://issues.omg.org/browse/DMN13-132.  I'll write a proposal to adress it.

**Comment by agilepro** [comment]
The proposal can be accessed at:  https://issues.omg.org/issues/DMN13-132

Any more questions???

**Comment by agilepro** [comment]
Would like to know if this has been discussed.  The issue does not show any progress.

**Comment by StrayAlien** [comment]
@agilepro - the tests mentioned are resolved with the recent (amended) PR for list functions.  The notion of coercion to null for values outside of a semantic domain is covered in 0082-feel-coercion.  The issue shown above not not specifically deal with that (I believe).  I am happy to close this and if any crops up deal with it on the 0082 suite.
