### ISSUE TITLE
Travis CI?

### ISSUE THREAD

**Issue by deostroll** [dmn-tck/tck#212]
Can anyone shed light on the travis CI integration? I am concerned about the image used for containerization. Will it support a javascript test runner? I assume this is to keep vendors abreast with any update in test cases, so their engine may run any new test cases which are added. But I am not sure of the environment such tests will run with. Looking at the yml file I don't have a clue about that.

**Comment by tarilabs** [comment]
@deostroll Hi Arun, as documented in the MoM of the DMN TCK meetings (I seize the chance to invite you to join as documented here: https://github.com/dmn-tck/tck/wiki/Joining-the-Effort), we use the Travis CI first and foremost to Validate the DMN model from an XML validation perspective, and the XML of the test cases itself. 

In other words: We use Travis CI mainly to ensure if any new test are added, or modified, we have at least an immediate XSD validation check.

Additionally, as an optional opt-in, some Vendors have decided to include also their engine to run during the CI build; but whatever is the result of their run, it is not impacting on the Travis Run result green/red itself, but you can check it by going into the detail of the Travis Run page. We also use this to gain some confidence during new DMN1.2 tests, but again is an optional step.

If you are a Vendor and you implement via JavaScript we welcome you to join the TCK and submit your results; this will make your Product/Project results show on the TCK website.
Additionally, we also welcome you to submit your TCK runner, if license permits.
Additionally, we also welcome you to opt-in in the Travis CI build step if you want, and if there are any limitations with the Travis I would be glad to support in working out for eventually a solution to that.

Hope this helps and I'm available if any further questions or doubts!
