### ISSUE TITLE
Who is the OMG Jira admin?

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#245]
There have been a few clarifications posted to OMG lately.  Seem I don't have access to JIRA.  I get:

![image](https://user-images.githubusercontent.com/12524254/52155024-bef28d80-26d4-11e9-9357-7247261ae176.png)

I can do a password reset etc and I have signed up.

Anybody know who I contact to get it sorted?  @agilepro ?

Greg.

**Comment by agilepro** [comment]
Are you a member of OMG?   I am not so I am not able to see these.  But if you are a member you should be able to see them.

What URL did you try to access?

**Comment by StrayAlien** [comment]
Thanks @agilepro - I was just attempting to follow the issue links in some 'Waiting for RTF' PRs.  Like this one: https://issues.omg.org/browse/INBOX-819.

It permits me to do a password change but then says I'm not permitted to log in.  I thought somewhere I did sign up for JIRA but maybe not.  I sure didn't become an OMG member.

So this is kind of a bit awkward - people here can raise issues with OMG and provide a link ... but the rest of us can't see them.  Not quite open!

Anyways, I have sent bd-team@omg.org an email to see what I can do.

**Comment by StrayAlien** [comment]
Actually, if I replace 'browse' in the URL with 'issues' as https://issues.omg.org/issues/INBOX-819 I can see it. :-)

**Comment by StrayAlien** [comment]
closing
