### ISSUE TITLE
Strings should count Unicode code-points

### ISSUE THREAD

**Issue by agilepro** [dmn-tck/tck#248]
Submitted a ticket with this content.  JIRA really trashed the text significantly adding newlines and dripping some characters, so including the entire content here in original form:

Key: INBOX-825
Status: pending  
Source: fujitsu america ( keith swenson)
Summary:

On page 110, rule #66 gives these escape sequences:

string escape sequence = "\'" | "\"" | "\\" | "\n" | "\r" | "\t" | "\u", hex digit, hex digit, hex digit, hex digit;

Using the hex character value notation "\uD41A" you can only four hex digits which is not enough to specify the entire Unicode character range. The spec specifically mentions that much higher values are allowed, and there should be a standard way to specify them without having to use the cryptic surrogate character pairs.

This suggestion is to add braces to allow variable length hex values in exactly the way that JavaScript allows:

"\u{1F40E}"

This is character 128,014 in the unicode set. To specify this character using surrogate pairs you would have to use: "\uD83D\uDC0E" which is complicated and confusing and is currently subject to discussion on whether this is valid or not within the current spec.

"A" = "\u{41}"

"è" = "\u{E8}"

"査" = "\u{67FB}"

"🐇" = "\u{1F407}" (Jira seems to crash if I include this character)

It is nice because you actually use the Unicode code point value, and because of the braces you can specify a variable number of hex digits so the entire Unicode set can be easily addressed. The precedence for this syntax is set by JavaScript.

https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf

See page 218 where it defines this (slightly translated):

UnicodeEscapeSequence ::
    \u Hex4Digits
    \u { CodePoint }

This will not conflict with any existing implementation since the opening brace was not allowed in earlier implementations. The new allowed syntax could be used in DMN 1.3 and higher.
Reported: DMN 1.2 Beta 1 — Fri, 8 Feb 2019 19:06 GMT
Updated: Fri, 8 Feb 2019 19:06 GMT
Attachments:

**Comment by StrayAlien** [comment]
@agilepro nice. 👍

**Comment by StrayAlien** [comment]
@agilepro - this hasn't really held up any tests and is being tracked in RTF.  Like the 'recursion' issue i raised I gather this is an FYI?  Do we need to track it here?

**Comment by agilepro** [comment]
Discussion in RTF.   Got a "hint" that the RTF is tending toward counting the number of "glyphs".  There is a spec from Unicode to define how to find the "glyph boundaries".  

Another vendor mentioned that substring is affected as well with regard to counting characters.  The spec does not discuss this. 

Normalization is another topic.

**Comment by opatrascoiu** [comment]
Several links from Unicode

abstract characters
https://unicode.org/glossary/
http://www.unicode.org/versions/Unicode12.1.0/ch03.pdf#G2212

counting UTF-32 codepoints it's an option.

**Comment by agilepro** [comment]
In discussion, we decided to propose that string length and string index is the count of 32-bit code-points.  This is consistent with what the RTF has said, and it is well defined, there are Java implementations for this.  If there are no contrarian remarks in the next week we will consider this a decision.

**Comment by StrayAlien** [comment]
@agilepro - dare I ask ... (my unicode kung-foo is not as developed as yours) is that the way it was in the original string length PR?

**Comment by agilepro** [comment]
Yes, this is exactly what you initially proposed, counting code points.  Sorry.   I still think it is unpractical, but FEEL is nothing about being practical.  I still want to poll TCK members for consensus.

**Comment by StrayAlien** [comment]
Hi @agilepro - thanks.  Honestly, I am not religious about any particular way here.  My question above was for clarification - not to be, well, stupid about it.  

With the initial PR I just went for what made more sense to me.  I guess, even if it is not correct according to the letter of the unicode law, perhaps maybe it makes more sense more often than otherwise.  At any rate, us doing it all the same way is the important thing.

> but FEEL is nothing about being practical

That made me laugh. :-)

**Comment by agilepro** [comment]
Closed because we are tired of dealing with this point.   Currently the tests are as the tests are, and if anyone wants a change they can make the change.
