### ISSUE TITLE
between operator tests for strings

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#249]
The file contains two tests with string operators. For example, the expected value for 

            `"c" between "b" and "d"` is `true`

According to the DMN 1.2 spec (see page 96)

`String and Booleans can only be compared for equality: the semantics of strings and Booleans equality is as defined in the specification of fn:codepoint-equal and op:Boolean-equal, respectively.`

According to Table 50, `e1 between e2 and e3` is equivalent to `e1 >= e2 and e1 <= e3`
 
Based on the above, "c" <= "b" is incorrect, hence the expected value should be null. 

Am I missing something? Lets discuss.

**Comment by opatrascoiu** [comment]
I just found out another place in DMN :  `Table 49: Specific semantics of inequality` that allows relational operators for strings. 

I'll close the issue.

**Comment by tarilabs** [comment]
Yes Table 49.
