### ISSUE TITLE
Chapter 11 example: is it correct?

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#253]
Hi all,

I am wondering if anybody has actually run the spec chapter 11 example to assert it outputs what the spec says it should for the given inputs.  The spec is a little awkward there getting some diagram numbers wrong and so on, and given there are so any other issues with the spec I'm not blindly trusting  it ...

Why do I ask?  Coz I've run it and not got the 'expected' result and before I invest 20 hours trying to figure why ... I think it best to make sure is correct!!

Greg.

**Comment by tarilabs** [comment]
Ciao Greg,
I got an OMG RTF jira opened already a while ago about it: https://issues.omg.org/issues/DMN13-98
There are chances it describes the same issue you encountered, but up to you to confirm

**Comment by StrayAlien** [comment]
Heya Matteo, I *absolutely* owe you a beer on that one! :-) . Phew.  I did see those numbers and thought that 100000 expenses seemed a bit weird.  But thank you, you have saved a lot of debugging time.

Beer.  👍 

(btw, I think it is likely a good 'integration' test to have in the TCK test cases)

**Comment by StrayAlien** [comment]
closing.  thanks again mate.
