### ISSUE TITLE
Chapter 11 imports resolution

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#256]
The chapter 11 example uses an `import` element to import a BKM.  The example has that BKM in a filer called `Chapter 11 Example - Financial.dmn`. The model import element has no `locationURI` associated with it, just a matching namespace with the external file that contains the BKM.  Actually, the external file name is not mentioned at all in the model. 

I am not sure if I am missing something here or whether the example is incomplete in this area.  Without a locationURI, a DMN runtime would not know to read the file `Chapter 11 Example - Financial.dmn`.

However, the spec says:

> The location of the imported element may be specified by associating an optional locationURI with an instance of Import. The locationURI is a URI. 

I can't imagine why an import would not have a `locationURI` but anyways, the reason for my confusion here I guess is that the locationURI is _optional_.  If so, then maybe the example is correct and I’m missing an understanding of some ‘implicit’ thing?

I am looking to get started on some tests here soon and the whole 'what is a location URI' and what does it mean to a DMN runtime sounds like a can of worms ... but it needs tests ....

Many thanks.

**Comment by tarilabs** [comment]
Greg, I'm not entirely following you on this one.

I searched in the spec for "Chapter 11 Example - Financial.dmn" but that is not present in the PDF anywhere?
![image](https://user-images.githubusercontent.com/1699252/53626805-fd616680-3c06-11e9-8bbb-7ce8d3fae1b3.png)

I believe on the Ch11 example what you are referring to is this function call:
![image](https://user-images.githubusercontent.com/1699252/53626859-22ee7000-3c07-11e9-9d2a-e0b40e5de66d.png)

To a BKM named "PMT" imported under the name "Financial"
![image](https://user-images.githubusercontent.com/1699252/53626912-3d284e00-3c07-11e9-9970-f89842e4e1fd.png)

Wrt to "locationURI" in my perspective is not an absolute mandate of the spec to work across different Vendors and Implementation, as that by the spec:

1. is optional,
2. and as not all URIs are URLs hence would have required to specify all mandatory protocols.

In my understanding, "locationURI" is an helper attribute for an implementation to locate the imported model in a repository, for instance, `locationURI="commons/financials.dmn"` in a organization repository would expect to locate a model with the expected namespace by resolving that URI.

I cannot advise for all implementation, in "my" case starting a DMN runtime requires to indicate the list of DMN model(s); if any model in the list is importing another model, the runtime checks the referenced model is available in the list or via the locationURI.

Hope this helps.

**Comment by StrayAlien** [comment]
Hi Matteo, yes, that is helpful thanks.

But, re the 'not in spec' thing is my fault.  Sorry, I actually meant the example DMNs supplied here:

https://www.omg.org/spec/DMN/20180505/examples.zip

The example dmn has an import named 'Financials' but no locationURI, so it seems no DMN runtime would be able to do anything with it at all - hence my wondering if it is 'incomplete' or I have missed something.  The reference d`PMT` being is in a file accompanying the main DMN, but the file is not referenced.

I do get the nature of URI being vendor specific - who knows URI scheme each vendor might support, but I also feel this functionality is a very important part of the spec and somehow we should provide tests.  Not exactly sure how, but my feeling is maybe the tests only ever reference files in the same folder with no URI scheme and we leave it up to vendors to have a test runner capable of loading and feeding that to their runtimes.  No `xml:base` tests and somesuch. 

All thoughts welcome.

**Comment by tarilabs** [comment]
So now we are speaking of the TCK test infrastructure if I understand correctly; if there is a consensus in the TCK test file for some additional attributes are required in order to make import work, I'm happy to support for the changes too.

So far here: https://github.com/dmn-tck/tck/wiki/How-to-Create-a-Simple-Test-Case#naming
we have:

> The DMN file also by convention has the same name as the test set as well. Thus the DMN file would be named "0001-input-data-string.dmn" It is not required to have this name, because the test file actually specifies the exact name of the DMN file, but it is a convention used by the test runners to execute the tests.
> You might have some other files in the folder, but these are expected to be supporting documentation. Often a PDF files is included that shows the DMN diagram, but that is not required. These are ignored as far as the testing is concerned.

I believe by extension it allows for the case that in a given directory you have several TCK test .xml file, and several DMN model .dmn files.
When running for a specific TCK test .xml file, the runner would pick for evaluation the DMN model file corresponding to the `name` attribute specified in the TCK test .xml under execution, and imported model would be referenced from the same directory.

This in turn makes me believe _no change_ to the TCK test infrastructure is actually needed, although some Vendor's runner might need to adjust for this scenario, as we did not have test for DMN Import before as it was broken on DMNv1.1 (in Drools we supported DMN Import on v1.1 anyway by means of extension as needed).

If my reasoning has a pitfall and thus really requires changes to TCK test infrastructure / file format please let me know.

**Comment by StrayAlien** [comment]
Hi Matteo, I also think that no change should be necessary to test stuff if the `locationURI` is required to locate an external model - which the chapter 11 dmn XML example omits (the original reason for raising this issue).  

I kind of think that that dmn XML for the downloadable example (from the link above) is not correct in that it uses a BKM from an imported dmn file, but has no `locationURI` to that file.  But wanted to clarify in case I was missing something deep.  Sounds like (hopefully) I am not.

back to testing:  the spec does not specify what 'schemes' the URI may use, like http, or anything else, so in that sense any one could argue that even _attempting_ to write tests here may be outside the spec.

For example, a vendor may choose to support their own protocol/scheme, or may deploy models in a way that the location URIs only mean something to them.   Making up an example here, but something like `all imported models and resources like XML schemas etc are bundled into a single binary file for deployment and the URI is a locator into that binary file .... not an HTTP URI ....'  or a source control URI using a specific protocol .... whatever.

I think sticking to simple 'in the same folder' tests should be enough to test what we need, but, hopefully, we get no arguments about schemes etc.    :-)

**Comment by tarilabs** [comment]
In summary it seems to me we agree on:
- no expected change to TCK test infrastructure / file format
- we can reasonably expect imported DMN models need to be available in the same TCK test case directory (if any of the DMN model is importing other models)

On other hand. Personally, were you say:

> I also think that no change should be necessary to test stuff if the `locationURI` is required to locate an external model - which the chapter 11 dmn XML example omits (the original reason for raising this issue).

I don't concur with your conclusion that the chapter 11 dmn XML example is omitting a necessary attribute.
The importing model specifies
```
<semantic:import namespace="http://www.trisotech.com/dmn/definitions/_5e8e877a-af87-434b-9c36-ed51c8d6b514" name="Financial" ...
```
and there is another DMN model file in the zip with the required coordinates (namespace ending `...6b514`).

As the DMN spec does not specify APIs requirements, in analogy it does not specify how an error has to be reported, one could argue as soon as you are able to feed into a DMN implementation the overall DMN models and you want to evaluate the `Chapter 11 Example.dmn` one, is up to the specific DMN implementation to figure out how to locate the imported model by means of the API or the (optional) `locationURI` attribute as needed.

**Comment by StrayAlien** [comment]
Thanks Matteo,

Re:

> I don't concur with your conclusion that the chapter 11 dmn XML example is omitting a necessary attribute.

I was thinking you might say that.  :-)

The matching namespace in the external file was one reason why I thought we might be expected to do some 'magic' rather than use the `locationURI`. I am interested to hear how others feel as well but if the collective answer is indeed 'magic', then I think it would be a shame - one more thing to limit interoperabilty.  But important to know about for the creation of tests.

**Comment by agilepro** [comment]
Greg,

We discussed in the meeting today.  The list of comments has meandered a bit and I am not quite sure exactly what the proposal or question is.  We felt it would be helpful to have a concrete case, such as a test that focuses exactly on this issue without the rest of the complication.

Would you be able to make such a test case so we can discuss it.  If not, Matteo might be able to, but I thought I would ask you first.   Thanks.

**Comment by StrayAlien** [comment]
Hi @agilepro , @tarilabs.  I'd rather get things clarified if we can before I invest the time. :-)

But I think I get what is going on and can summarise, it basically boils down to "how a DMN runtime finds imports is proprietary".  The spec does not provide enough information to have a consistent impl - and I agree that it would be very hard for it to do so.  For the basic reason that runtimes will package and deploy artifacts differently.  This is supported by:

* the locationURI attribute on import is _optional_ - which means there is no requirement to inform other DMN runtimes about resource location - thus a runtime implements its own finding mechanisms.
* Even if a DMN import does have a locationURI, there is no guidance (beyond its _relative_ location to the importing DMN) as to what a URI actually is.  http? ftp? tftp?  (https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)  

So a runtime has pretty much free-reign to decide how to find imports and what a URI actually means. Fair enough.  Likely how things are found will depend on how the given product's 'packaging and publishing' mechanisms work.  

Re the chapter 11 example:

It does not provide a locationURI to the being-imported DMN.  The importing DMN has an import namespace and there is a file in the same folder with a matching namespace.  No locationURI.  If the example is truly runnable by someone's runtime then they have their own magic namespace-matching mechanism for finding that import file.   Others will not share that same magic mechanism, nor do they have to.

Additionally, I believe the namespace on an import is how the _importing_ DMN refers to the imported  resource and _not_ a namespace _inside_ the imported resource (like the ch11 example may be using).

So all up, imports are proprietary.

I suggest that for writing tests here we stick to using a locationURI on an import that is a pure relative URI - being just a dmn file name in the same folder as the test.  People's test runner can feed those into their runtimes as they see fit.

For ch11 example - we would simply add a locationURI to the ch11 import element that has the import file name.

**Comment by StrayAlien** [comment]
Closing off. Tests on the way. Likely chapter 11 dmn will be included albeit with a locationURI.
