### ISSUE TITLE
Decision Services - clarification before (more) tests

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#259]
Hi all,  I thought I'd just open out some discussion here re how Decision Services are intended to work.  We have done a simple noddy impl here but .. the more I read the docco in the spec I'm pretty convinced we don't have it right at all, nor fully understand it.  

I'd like to ask some questions to help those that haven't yet implemented it - please correct me if I am wrong but according to github neither jdmn or Camunda have implemented Decision Services as yet, so like everything else here - this is for the benefit of all.  If those project have implemented it then no offense meant - I just pulled the code and look for DecisionService on all branches to see what was there.

Apols if this is a bit long but I think this is very important to get right.  If I may ask, Please read carefully.

__Invocation__

Spec says to invoke 'internally' it is like a BKM, but it has no formals params.  Indeed, formal params could be determined from Input Decisions and Input Data.  Granted each of those items is a `NamedElement` so we could invoke a DS using _named_ params as well as positional.  The InputDecision and InputData XML elements are a `sequence`, so we can also determine the 'positional' nature of params using that order.  The "Execution Semantics" section for DSs says input data goes before input decisions.  So, we could say:

> __Question 1__: Can DSs can be invoked 'internally' using inferred Formal Parameters (and their respective types) both positionally, using the order of "input data then input decisions" in the order given in the DMN, and as named params using the names of the input decisions and input datas.

__What is an Input Decision .. really ?__

The notion of passing in the result of a decision as an input decision' has me somewhat confused.   

For 'internal' - it means the decision/BKM/etc invoking the DS really has to have a requiredDecision on that same input decision to evaluate it first and then pass the result as a param to a DecisionService.  That doesn't seems logical to me.  

For 'external' it means a caller of the microservice has to have evaluated that decision beforehand to pass it in, almost like an inputdata. 

In both cases the DS is not 'evaluating' the input decision (like a Decision 'evaluates' requiredDecisions before its own execution).  It is just an incoming value like inputData.

> __Question 2__ : So what is the point of an InputDecison? - if we must pass a decision 'result' into a DS as a param then it is just a _value_ isn't it - some more input data?  Does a DS invocation _ever_ evaluate an InputDecision like a Decision evaluates a required Decision?

.. is it perhaps that a DS creates a new scope and these input decision param values represent the resolved `variable` for the input decision _in that scope_ such that any other decisions or drg elements invoked during the DS invocation use this 'pre-resolved' one? 

__What are DS inputs ... really?__

A couple of things here really.

Firstly:

Just like input decisions for a DS, the inputs get passing in as parameters, but as far as I can tell, the _actual_ DRG input elements are never interrogated for their values .. no need to - the values came in as params.  

> __Question 3__: So what value does a input serve here?  Like the input decision speculation above above is it to kind of put an input value into a DS scope so anything that requires that input gets the param value and not the 'global' value?  

Secondly:

The figure 5.10 text says "The service requires Input data 1 and Input data 2, but not Input data 3."

If I invoke DS 5.10 as a microservice, in practice I really also must supply 'Input Data 3' in the request data.  Otherwise 'Decision 3' has no inputs.  So, it seems to me that the _real_ required inputs of a DS is the (recursive) collection of required inputs of its output decisions and encapsulated decisions and their required decisions and so on.

If I were to say, generate an openapi spec purely on the 5.10 DS interface it would not require 'Input Data 3', but then:

> A request to the service is “valid” if instances are provided for all the input decisions and input data required by those decisions which need to be evaluated, i.e. (in the simple case) all the encapsulated decisions, or (assuming the optional parameters above) any requested decisions and their required sub-decisions which are not already known.

Which _seems_ to suggest that a DS request _needs_ those extra inputs that are not in its interface. So oddly, a DS microservice is one that you have to pre-evaluate the input decisions _yourself_ before calling it, and then supply all additional inputs that are needed but not part of the DS invocation interface ...

> __Question 4__:  does the real interface of a DS include the sum of all inputs required by anything it executes.

Apols for the tome, but it all seems a bit weird and wobbly. 

All thoughts welcome.

Greg.

**Comment by tarilabs** [comment]
Greg, my perspective below

A1. Correct, when you invoke positionally the order is defined by list of input data and list of input decision. For the order in the list reference is made to the `inputData `and `inputDecision` in the xml.

A2. It is about re-use (of the Decision Service). The whole point of Decision Service is to enable re-use of decision logic also from a DRG perspective. Because a Decision Service is also an invokable, it has some parameters; in a way, if the value of the parameters is coming from an InputData drg element or a Decision drg element, from the perspective of the parameter value itself, it should not make a difference, is a transparent concept to the parameter value. So when you invoke the DS directly, you must satisfy all required parameters. If the value of one of the parameter is coming from the model from a Decision, when invoking directly the DS it must be supplied and valorized like any other parameter.

(I'm not sure I follow Q3)

A4. I am not on the same on this one. A DS input(Data/Decision) is defined by all requirement edges crossing as incoming the boundary of the DS. This will determine `inputData `and `inputDecision` too. When you invoke a DS, you need to supply [the values] to all these parameters.

Hope this helps.

p.s.: in Drools we implemented Decision Service even on DMNv1.1 by means of extensions to fix the problem which were related to v1.1, and when moving to DMNv1.2 the implementation can fully rely on the DMN specification itself.

**Comment by StrayAlien** [comment]
Hi Matteo,

Thanks for taking the time to answer.  I know that was a long one.

Re (q1) position params - would you say they can also be named params?  I would think yes.

Re q2/q3 (I think q3 is kind of answered by q2 thanks) - a further clarification if I may:

Given either an input or decision value is passed to a DS as a param  - say, in the DS ‘execution tree’ there are other DRG elements that use the same input, or require the same decision.  I am guessing these input/decision param values hit the scope and are resolved in the same way for all things in the execution tree that use them?  - in effect, the are bound _within_ the scope of DS execution to their associated variables ?

Re q4: okay seems the interface to a decision service and the interface to a (say) microservice calling a decision service are different things. 
  
Thanks again.

**Comment by StrayAlien** [comment]
closing as I think I have a handle on it.
