### ISSUE TITLE
Are date/time zones case sensitive ?

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#264]
A change here: https://github.com/dmn-tck/tck/pull/262 prompted clarification on whether time zones in DMN should be parsed in a case-sensitive or case-insensitive manner.

The DMN spec refers to iana zones but iana does not mandate either way.  It is up to the implementation.

https://data.iana.org/time-zones/theory.html

> Do not use names that differ only in case. Although the reference implementation is case-sensitive, some other implementations are not, and they would mishandle names differing only in case.

Worth seeking clarification on I feel.

**Comment by agilepro** [comment]
It seems to me that the only option we have is to treat the IDs as case sensitive.   We should not use case insensitive, and an implementation *might* return an error is get the wrong case.   Java has an option to relax this, but we can not rely on that.

The tests should always be careful to use the right case strings.

**Comment by StrayAlien** [comment]
HI @agilepro , personally, I think case-insensitivity is a better and more flexible option as iana does not say it is case sensitive - and we may expect input data from systems with iana-compliant timezones that need not be are not case sensitive (like Java itself).  FWIW, I've got case-insensitive turned on.  I do agree that in tests we should stick to the same case as the iana zones (and make no assertions on case sensitivity)  

But, if the goal is DMN model portability, then I think it is worth getting clarification.  To that end I have raised `INBOX-836`:

https://issues.omg.org/issues/lists/unclassified#issue-44836

Greg.

**Comment by agilepro** [comment]
Issue is still in the inbox, and the RTF needs to discuss.

**Comment by tarilabs** [comment]
https://issues.omg.org/browse/INBOX-836

**Comment by agilepro** [comment]
INBOX-836 is still in the inbox!   What is up with that?   Two weeks.   It is a manual job to bring it in.   Not the fastest.  

This seems like a simple but important issue.

**Comment by agilepro** [comment]
Hoping for discussion next Tuesday in RTF

**Comment by StrayAlien** [comment]
tests now reflect uppercase.  Issue is in with RTF for discussion.  It can be tracked there.  If they arrive at anything different then we can action that. Closing.
