### ISSUE TITLE
Most of our test definitions names are not valid FEEL names ...

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#273]
Yes - I know that is definitely a click bait title.  :-)  Apologies for that, but fun anyways! :-)

If I include a DMN model 'verifier' in my test runner, less than 200 out of about 1640 (including all 'unmerged tests') pass. Most fail due to the fact that the name of the definitions elements of their model starts with a digit.

Or do I have it wrong?  Or do we care?  I know they're not actually reference-able. But, worth noting for the sake of correctness.

Comments welcome.

**Comment by agilepro** [comment]
Name of a model does not need to be constrained by these rules.  We discussed and feel this is not an issue.  Greg was on the call and seems like he agreed as well.  So closing this.
