### ISSUE TITLE
Bug: Wrong InputNode name in test file: 0001-filter-test-01.xml

### ISSUE THREAD

**Issue by arthware** [dmn-tck/tck#28]
The inputNode in the test file is called "Employee" whereas in the model the InputData is called "Emplyoees".

I think this is the result of a mistake during merge conflict resolution.

**Comment by etirelli** [comment]
You are correct, the regression was introduced here:

https://github.com/dmn-tck/tck/commit/b95dbd7c4ec2fc369205df229f27f04f1edec37a#diff-cbd12256bd219c20d326d253df4b151aL11

Thanks for reporting!
