### ISSUE TITLE
Non-compliant tests 0015-all-any and 0019-flight-rebooking 

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#281]
The above tests have not been migrated to DMN 1.2. (e.g. typeRefs contain the feel: prefix)

**Comment by StrayAlien** [comment]
Hi @opatrascoiu, are you saying they should not be?  That is effectively what I have done here - migrate them to 1.2.  Or have I not missed some 1.2 stuff ?

**Comment by StrayAlien** [comment]
I've got some PRs in on them at the moment.

**Comment by opatrascoiu** [comment]
great. thanks

**Comment by agilepro** [comment]
Octavian, can we close the issue then?

**Comment by StrayAlien** [comment]
@opatrascoiu btw, if you got  strange (now missing) comment from me on this issue it was because when I first saw it I thought you were commenting on one of the PRs I had in.  I got it wrong so I deleted the message.  Apols!
