### ISSUE TITLE
Recursive ItemDefinition and application to DRG Element

### ISSUE THREAD

**Issue by tarilabs** [dmn-tck/tck#283]
I believe a separate issue for a discussion would be more appropriate, to avoid trying to a specific PR.

With reference to https://github.com/dmn-tck/tck/pull/279#issuecomment-480351850

Say one has an ItemDefintion for modeling an `Employee`. itemComponent(s) of Employee are `name`, `surname`, ... and `supervisor ` which is a circular reference to `Employee`.

If you have a common case of employee, you could model its supervisor by something like:
![image](https://user-images.githubusercontent.com/1699252/55651331-89f3db80-57e8-11e9-8472-8884c53b4b49.png)
which is fine.

But how could you model a "freelance" where you want to express such Employee is supervisor of itself? The data structure would allow it, but semantically on the DRGElement you cannot, because a DRGElement cannot reference itself, cannot have a circular _informationRequirement_ reference to itself.

Thoughts please?

**Comment by StrayAlien** [comment]
Thanks @tarilabs ,

Nor can you have circular data-relationships in JSON - it can't be serialised.  But that doesn't mean JSON schema doesn't support cycles.  Indeed, the JSON Schema itself is a JSON Schema with self references all through it.  It is a tree (or acyclic data graph of JSON schemas) - which is what I think the circularity of types is there to help us with.

I think whether ItemDefinitions can be circular is a different thing to whether DRG elements can be.   I think it is true and correct that DRG Elements should not be circular.  They are to describe a decision flow, not a data structure.

I imagine the true users of circular data structures are BKMs.  They are also the only DRG element that is is even possible to consider recursion with.  Despite being an invokable, you cannot recurse with a decision device as it has no logic, and invoking it again from somewhere within its calls tree would break the "DRG elements must be acyclic" rule.

**Comment by tarilabs** [comment]
Closing, basing on example of JSON _grammar_, for example here https://www.crockford.com/mckeeman.html members defines a self-recursive alternative in the grammar rule for members.
