### ISSUE TITLE
Recursion support issue opened with OMG 

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#284]
As an FYI I have opened and issue with a spec change suggestion to make recursion formal in the spec.

https://issues.omg.org/issues/lists/unclassified#issue-44962

Inbox item INBOX-842

Hopefully that is not a 100th time the request has been made! :-)

Here is the text:

The definition of "well formed" for a BusinessKnowledgeModel excludes the notion of the encapulatedLogic of a BusinessKnowledgeModel being able to invoke itself to permit recursion.  There is no means to define a 'self' relationship via knowledgeRequirements - the spec forbids it. 

However, vendors are currently supporting BusinessKnowledgeModel recursion simply by permitting a BusinessKnowledgeModel's encapulatedLogic to invoke the contained BusinessKnowledgeModel as a function using the contained BusinessKnowledgeModel's name.  I propose we formalise this in the spec.  

I propose that after the definition of well-formed on page 56/57 (repeated below): 

"An instance of BusinessKnowledgeModel is said to be well-formed if and only if, either it does not have any knowledgeRequirement, or all of its knowledgeRequirement elements are well-formed. That condition
entails, in particular, that the requirement subgraph of a BusinessKnowledgeModel element SHALL be acyclic, that is, that a BusinessKnowledgeModel element SHALL not require itself, directly or indirectly. "

The following paragraph is added:

"However, the encapsulatedLogic within a BusinessKnowledgeModel may invoke itself in a recursive manner by using the name of the containing BusinessKnowledgeModel as an invokable name."

**Comment by agilepro** [comment]
Does anyone here disagree with this?   I think we agree.

Are there any tests waiting on this?  If we agree, then we should go ahead and move forward.  If the RTF decides differently we can change the tests later.

**Comment by StrayAlien** [comment]
This was an FYI, not really an issue, so closing.
