### ISSUE TITLE
error in issue DMN13-133 ?

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#285]
@tarilabs,

Re https://issues.omg.org/issues/DMN13-133

Should the last line in the corrected example be:

`[1, [2.1, 2.2], 3, 4, 5]` and not `[1, [2.1, 2.1], 3, 4, 5]` as given in the link above?

(note the 2.2 vs 2.1 in the second element)

**Comment by tarilabs** [comment]
Thanks for reporting Greg, but in the already-voted proposal that was already fixed.

**Comment by StrayAlien** [comment]
@tarilabs - thanks mate.  Excellent. Time to put in a test to assert it.  :-)
