### ISSUE TITLE
suggestion: move 'integrated' tests into own folder 

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#293]
All, I'd like to suggest moving the non-unit 'integration' test tests into their own folder. Something like, say, `level-3-integration` (or whatever).  Examples would be 0004-lending, or 0014-loan-comparison and so on.

They sure are valuable, and I am very (very!!) happy to have them in the suite, but they are not focused tests - if they fail, any one of 50 things could be wrong.  

My feeling is the TCK should cover, in fine detail, the things in the spec and if something fails, the test name and setup should help narrow it down for the implementor.

Please understand, in _no_ way do I recommend losing them - in fact, I think as other 'representative' examples comes along then cool, get them in.  Many implementors will not have access to ready-made complex model examples and they are very useful.  But presently, some of them are are the sole source of some verifications - which is a bit muddled.

When TCK 'unit test' coverage increases to such point that those 'integration' tests are no longer the single point for some verifications, and we have confidence in those targeted unit tests, then we can perhaps make the 'integration' tests optional.    

Happy for thoughts and comments,

Greg.

**Comment by tarilabs** [comment]
While I appreciate some of the thoughts raised in this issue, specifically the reasoning to have "focused" test, I do not agree with this conclusions:

> then we can perhaps make the 'integration' tests optional

Moreover, having separate folders might give the wrong impression some models are not really "standard" or "beyond the spec" and we have already a separate folder for that.

The purpose of having a standard is such that even complex, real use case DMN model execute the same across implementation.

For "focusing" the tests and facilitate implementors in case something is wrong, we can always have fine grain tests like I just appended for the CH11 example, that is **_providing a test for the supporting Decisions_**.

As @agilepro always invite people to submit "real" DMN model from my perspective the CL2 and CL3 current folders are more than good for the job.

I will have no strong objection if someone makes additional folders, amends the TCK infrastructure to support them, and update all the wiki and related document; however I'm not convinced yet this is a totally good idea for the reasons I tried to summarise above.

What do you think?
Also, do you agree a fine-grain test can always be supplied for a complex model, to have as well "focused test" as part of a test case folder?

**Comment by StrayAlien** [comment]
leave as is then.  closing.
