### ISSUE TITLE
decision as information requirement when it has no expression

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#304]
WRT: https://github.com/dmn-tck/tck/issues/303#issuecomment-492527344

what would one expect when a decision with no logic is an information requirement  to another decision.

**Comment by tarilabs** [comment]
Similarly to what you would do when you invoke a decision service which has an information requirement a required _decision_: you need to supply it (externally) in order for the evaluation to [continue to] work successfully --e.g.: like for decision service invocations, you need to satisfy the requirements.

**Comment by StrayAlien** [comment]
Okay - I get the usage for a decision service when it is input decision and thus it type being of importance.  But that is quite specific circumstance.  And, if supported, should be tested for.

What about outside of that?  I don't recall seeing anything in the spec relating to supplying a decision with its own result ('externally' meaning by 'input data' or pre-populating the 'variable' I guess).  Or did I miss it ( .. it would not be the first time).

**Comment by agilepro** [comment]
Every name in the DRG must be unique.  This means that input from the tests could be providing 'result' values for decisions in the model, and those results should be used for further computation instead of recalculating again.   The supplied decision results take precidence.   We shoudl probably have some tests that test this.

**Comment by agilepro** [comment]
This is low priority, but leave this issue in place to remind us to create them (eventually).

**Comment by StrayAlien** [comment]
I can't say I agree that we can supply a pre-cooked result for a decision - isn't that why we have the 'inputData' DRG element ... ?

Just because DRG names are unique doesn't necessarily imply that because you supply data with the same name as a decision it takes 'scope' precedence.  I don't interpret that in the spec anywhere - but I could have missed it. 

However, if it is indeed the case, then perhaps it ought to be mentioned in the spec.  It sounds like something that should be explicit - not implicit.

**Comment by tarilabs** [comment]
To me is more than explicit in the section of Decision Service, namely the input Decision. A Decision Service is always a subset of the whole DRG.

**Comment by tarilabs** [comment]
I would have no problem to narrow the scope of the original proposal if any Vendor is opposing the idea and simultaneously raising a DMN RTF ticket to explicit the extension of the scope, so that until the DMN RTF ticket is resolved this on TCK would need to limit to a Decision Service. Bearing in mind the DMN spec is a bit vague on the general interface to invoke a DMN evaluation anyway..

During the TCK meeting there was consensus this is the common interpretation.
On my perspective, this is foundational from the Decision Service clause.

After all, you can always define a Decision Service having an Input Decision without a decision logic, and have an Output Decision with a defined decision logic, with information requirement the one without logic.
It however doesn't change the fact from the DRG perspective there is still a Decision with a decision logic depending on one without a decision logic.

**Comment by StrayAlien** [comment]
Thanks @tarilabs, I do think we should limit it to decision services.  Btw, I never got to saying that your insight on "decisions without logic" being okay for a decision services was a very good one.  Well done.  Honestly, that didn't occur to me, but after you said it, it made perfect sense.  Nice one.

Why do I think it should be decision services only?  It is about APIs, interfaces and reducing breaking changes in contracts.  Let me explain:

A decision service defines a contract for invocation - it is _itself_ an API definition - cool.  So "given these inputs of structure 'blah' I will produce a result of 'blah blah'.  Such an API definition is the external contract.   With such a contract you can emit openAPI or SOAP defns etc for other tooling to incorporate and use in an enterprise.  It is a contract.

API contracts should _generally_ remain stable. - if possible!

With a decision as an endpoint, its contract it effectively the sum of the inputData plus decision service inputs required to produce a result - so the contract is also fairly easy to contain and remain stable.

If it is possible to _override_ any decision (outside of a decision service) by providing some same-named input then _every_ decision also has to become part of the API contract.  That is, even if that 'overridden' decision is part of a chain of other things going on and is 'internal' - if it can be passed in as data it should be part of the contract.  It has to be.

If every decision can be overridden then every decision output structure has to become an optional part of the API contract.

This means that if you (say) refactor a model by (say) breaking up complex 'internal' or 'transient' decisions or making them a BKM or putting them in an imported model because they are shared etc ,  then by implication the external API changes in a breaking way. Which is not great.

I hope that makes some sense.   decision services _are_ a contract, but permitting overriding of _any_ decision (outside of a decision service) means unnecessary changes in an external contract.  It is  exposing internal operations as part of an external interface.  

Not great.   Again, hope that makes sense.

(and yes "the DMN spec is a bit vague on the general interface to invoke a DMN evaluation" is _absolutely_ true!)

**Comment by tarilabs** [comment]
Now your argument depends on the definition of a Contract: if I take by analogy a Java interface, this could translate into overloaded methods, or single method but with an (optional) varargs for the "externally supplied" decision values. I don't see how this is a problem per se.
Do you actually want to encapsulate some logic, for the sake of encapsulation and/or reuse? That is indeed the role for which imho Decision Service are designed for; this is an orthogonal consideration of the previous argument.

I respect your perspective, but I don't share it.  I hope I was able to convey in my previous comments why.

As anyway I respect your perspective, as mentioned, I will then provide as a concrete proposal a model where the Decision without decision logic is part of the input decision(s) of a Decision Service --from my perspective it doesn't make that much difference and, most importantly, the original goal would be achieved anyway.

**Comment by StrayAlien** [comment]
Hi @tarilabs, thanks. I believe it does make quite a difference.  Sometimes these small things do.  I'll have one last go to see if I can convince you and @opatrascoiu .  :-)

The varargs thing is not really what I mean here and not really correct. For one - varargs in Java all have the same type - which decisions may not.  And a 'contract' that has a varargs Object type is not really a contract - it may as well be a map ... which is also not a contract really.  

Permitting arbitrary overriding of a decision via input is not a great idea on a number of fronts - including security, but starting with breaking encapsulation and promoting fragile public interfaces is a reasonable place to begin.

It opens other cans of worms as well - like "if I can arbitrarily override decisions via input, then can I override a decision used by a decision service that is _not_ part of the interface?".  

I believe people would say no, because that is not part of the DS 'contract'. It makes sense not to allow that ...

... but for a decision, outside of a decision service, why would we then permit it? Does that mean the 'contract' for a decision is then all inputs and decisions in its execution graph?  Sounds fragile to me - and it is exposing 'internals'. It all becomes pretty confusing and "in this case you can, but in that case you can't".  That is pretty smelly. 

However, I do think there is a valid use case for arbitrary overriding - and that is for decision 'unit' testing purposes - to enable the 'mocking' of dependencies for test purposes.  But I don't think it has any place at 'production' execution time.

On security: I'd not like to be the one explaining to a security or govt audit that anybody can override decision microservice internals arbitrarily to manipulate an outcome.    I don't even want to think about that!

I'll stop now.  :-)

> I will then provide as a concrete proposal a model where the Decision without decision logic is part of the input decision(s) of a Decision Service

thanks.

**Comment by agilepro** [comment]
Matteo will make a test case to discuss in specific about this.

**Comment by agilepro** [comment]
OK, PR #317 has been created so closing this.   We can discuss any remaining issue there.
