### ISSUE TITLE
The test case 0085-decision-services.dmn has incorrect encapsulatedDecision elements

### ISSUE THREAD

**Issue by SimonRinguette** [dmn-tck/tck#322]
Decision Service in that test case repeat the decisions as output and encapsulated:

```
    <decisionService name="decisionService_001" id="_decisionService_001">
        <variable name="decisionService_001"/>
        <outputDecision href="#_decision_001"/>
        <encapsulatedDecision href="#_decision_001"/>
    </decisionService>
```

I believe this is incorrect. In the spec, output decisions go over the line, encapsulated under the line. It is not possible to have the same decision in both zones.

**Comment by SimonRinguette** [comment]
I have provided a PR for a fix.

Please note that this is an issue for modeling more than execution as most engine will probably ignore the encapsulatedDecision element

**Comment by tarilabs** [comment]
sorry, I didn't know about the `Close ` github directive but appears have worked nevertheless, thanks again
