### ISSUE TITLE
Test case 0031: semantics of instanceof are not clear in the spec

### ISSUE THREAD

**Issue by etirelli** [dmn-tck/tck#35]
Test case CL3/0031 defines an item definition with a number of fields, and then declares variables of that type that do not contain those fields.

The spec, AFAIK, is not clear on the semantics of "instance of". For instance, if an item definition tCoordinate declares fields x and y. A context with a single entry x is declared as a coordinate, is this valid? I.e., is an object with only field x, but no field y, still a tCoordinate?

Some engine implementations define the semantics of "instance of" using duck-typing, due to the underspecification of types in the spec, and on those implementations, the object defined above is not a tCoordinate.

There is an open ticket with the RTF for DMN 1.2 to clearly define the semantics of "instance of" and types in general in FEEL. 

Until the RTF decides on a course of action, I suggest we avoid tests that include such ambiguity. 

Test case CL3/0031 should either be refactored to not fall into this problem or be moved to non-compliant until DMN 1.2 is published and the test adapted accordingly.

**Comment by arthware** [comment]
Hi Edson, thanks for pointing this out. As our type checks are not yet reliably implemented, this hasn't caught my attention. Our runtime is not strongly typed. I fixed this ambiguity and will create another pull request.

**Comment by etirelli** [comment]
Fixed by PR #38
