### ISSUE TITLE
Value expression of Decision regarding BKM - section 7.1

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#353]
Hi all - apols for the new year barrage! I've saved up a few questions / clarifications over the last few weeks (more after this one ...)

Section 7.1 outlines the value expressions for decisions when they related to BKMs - it seems to be pretty prescriptive and somewhat restrictive.  I was hoping to clarify what they really mean - I feel like I am missing something important here! :-/

> "If a decision element requires more than one business knowledge element, its value expression must be a literal expression that specifies how the business knowledge model elements are invoked and how their results are combined into the decision's outcome." 

That seems to mandate if a decision uses more than one BKM the value expression must be a literal expression.  Why not any boxed expression of my choosing?

> "If a decision does not require any business knowledge models, its value expression must be a literal expression or decision table that specifies the entire decision logic for deriving the output from the inputs." 

So if no BKMs are required then it has to be a DT or a literal expression?  Not a context or some other boxed expression?

> "Similarly, if a decision element requires only one business knowledge model element, but the logic of the decision elaborates on the logic of its required business knowledge model, the decision element must have a literal expression that specifies how the business knowledge model's value expression is invoked, and how its result is elaborated to provide the decision's outcome."

Not sure about this - it does not refer to the value expression like the two points above - just it must have a literal expression.  What if I wanted to (say) invoke the BKM as a boxed invocation inside a context (not as a literal expression) with that context value being further elaborated?

Many thanks,

Greg.

**Comment by brsilver** [comment]
Those are clearly bugs in the spec.  Any expression type should be allowed.

Bruce Silver

**Comment by StrayAlien** [comment]
Thanks @brsilver - everything I have seen supports what you say.  Seems so odd that this would even be in the spec.  It all seems so restrictive.

**Comment by StrayAlien** [comment]
closing.
