### ISSUE TITLE
Debatable / incorrect test case in CL3/0085-decision-services

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#386]
The test case below seems to be incorrect. 

```
    <testCase id="007">
        <description>passing a single input decision param with incorrect type</description>
        <resultNode name="decision_007_1" type="decision" errorResult="true">
            <expected>
                <value xsi:type="xsd:boolean">true</value> <!-- DMN13-163 Decision Service output value in the case of single output Decision -->
            </expected>
        </resultNode>
    </testCase>
```
I think the expected result should be **null**. Here is the rationale:
- the execution semantics of a DS is identical to the execution semantics of a FEEL function (see 3.4 and 10.3.2.13.2)
- according to 10.3.2.13.2 if the arguments do not conform to the argument list the result of the invocation is **null**.

In our case the input has a _number_ type that does not conform to _string_ (see 10.3.2.9.2 Type Conformance) and there is not conversion (see 10.3.2.9.4 Type conversions).

**Comment by StrayAlien** [comment]
Hi @opatrascoiu, good observation and TBH, I'm not quite sure where we landed on this.  But, here is a take:

Section 10.3.2.13.1 Built-in Functions says:

> Built-in functions are invoked using the same syntax as other functions (grammar rule 40). The actual parameters must
conform to the parameter domains in at least one signature before or after applying implicit conversions, or the result of
the invocation is null. 

Note the "after" applying conversions.

Then Section 10.3.2.9.4 Type conversions on when implicit conversions occur:

> Binding contexts in which the value of an expression is bound to a variable with associated type information
(e.g. binding actual parameters to formal parameters in an invocation, or binding the result of a decision’s logic
to the decsion’s output variable). The expression is subject to conforms to conversion.

(gotta love the typo in the above - 'decsion').  So the implicit conversion is to null, which conforms to string, hence the invocation proceeds.

Not 100% sure that is the case here, but the tests were thought through pretty thoroughly.  Happy for comments.

**Comment by opatrascoiu** [comment]
@StrayAlien You are right, I completely forgot about the _conforms To_ implicit conversion.

**Comment by StrayAlien** [comment]
Hi @opatrascoiu  - I'd be interested to hear what others think here.  My comments above were more of a (erm) comment thn a statement.  Those implicit conversions do take place and the func is invoked, , but that seems to contradict the "if the arguments do not conform to the argument list the result of the invocation is null" thing.

If returning null is enforced as per your comment, I get some test failures - the one you mention, and also in 0082 suite:

```
    <testCase id="decision_bkm_002">
        <description>pass non-conforming type to bkm - bkm
            input param is null coerced</description>
        <resultNode name="decision_bkm_002" type="decision">
            <expected>
                <value xsi:type="xsd:boolean">false</value>
            </expected>
        </resultNode>
    </testCase>
```

It is a similar thing and I have this sneaking feeling that you are correct.  I was expecting it to fall over for more tests, but I recall a discussion about invocaking built in functions (BIF)  with null-coerced params should give a null result, but, as maybe only one BIF accepts a null and the logic of all others will actually provide a null result when they actually _execute_ with invalid params, as opposed to the runtime short-circuiting the invocations and providing a null result.

There were some comments from @tarilabs re null results on the PR comment here: https://github.com/dmn-tck/tck/pull/238#issuecomment-497744315.    Has a look at the test `invoke_001`.  I think maybe that should also be a null if you are correct - it is invoking a BKM via an invocation element and the param is not type compatible.

Maybe re-open this and leave this get some more comments?

**Comment by opatrascoiu** [comment]
I am re-opening the issue to give others the opportunity to comment.

The paragraph from 10.3.2.13.2 that defines the type conformance for formal parameters and arguments is below:

```
The arguments n1:e1…,nn:en conform to the argument list [X1, ... Xn] if type(ei) conforms to ti before or after applying
implicit conversions or ti is not specified in Xi, for all i in 1..n. The result of applying f to the interpreted arguments
n1:e1…,nn:en is determined as follows. If f is not a function, or if the arguments do not conform to the argument list, the
result of the invocation is null. Otherwise, let c be a context with entries n1:e1…,nn:en. The result of the invocation is
FEEL(body, s’), where s' = insert before(s, 1, c) (see 10.3.4.4).
```

Based on the above the conformance of the list of arguments to the list of parameters should be checked both before or after applying the implicit conversions. If the arity is the same the arguments conform to parameters because the conformsTo implicit conversion transforms the argument to null which conforms to any type in lattice. Hence, the user functions, BKMs and DSs are always invoked. The user can check for nulls inside the body of the function. If the arity is not the same the result of the invocation is null as the function resolution fails (semantic error).

Looking forward for comments.

**Comment by StrayAlien** [comment]
@opatrascoiu - after looking at / thinking about this further I think your initial comment is correct (IMO).  The "according to 10.3.2.13.2 if the arguments do not conform to the argument list the result of the invocation is null." is just the easiest to understand and less prone to error all around.  

I think, as per my initial response above, it can interpreted by joining dots that invalid types coerce to null and therefore all invalid types eventually can just be passed to a function as null.  But .. (IMO), I don't think that is the _intention_.   That section quote re an invocation returning null for non-conforming types seems pretty explicit and just makes more sense.  That text is new for 1.3?

Given that for a BKM or DS is it not possible to mark a formal param as the equivalent of 'not nullable', it seems to make even more sense to do it.  In some circumstances, the _meaning_ of an function invocation can change with a null.  For example, some params of the `number()` are nullable - if a type mismatch causes a param to become null then the result may differ to what is expected.   

I vote "return null for invocations where types are mismatched".  :-)

**Comment by opatrascoiu** [comment]
@StrayAlien I had reached the same conclusion after some more thinking. The conformsTo conversion is not an implicit conversion like the others (e.g. convert to singleton list) as during the conversion information is lost. 

The conformsTo conversion is part of the error handling process: it's a conversion that happens when syntactic & semantic errors occur. In this case the error occurs at the function invocation level hence the result of the invocation should be null.

**Comment by StrayAlien** [comment]
Hi @opatrascoiu . Thanks. I'm happy with that.  Now to encourage other to chimes in and make it formal.  I get 3 test failures in the TCK if that is enforced.   We can add tests for it - there are a few functions that will accept nulls - like number(), and we can create tests that show they are not called with null-coerced values, but are called with actual null values.

**Comment by StrayAlien** [comment]
@opatrascoiu - why don't I lob that in with the 1.3 PRs I am doing at the moment (?).  That text is new to the 1.3 spec so I can include the changes for those three tests, plus maybe the number() tests I mention above.

**Comment by StrayAlien** [comment]
Add test `invoke_001` in `0082-feel-coercion` to that list of tests to be amended.

**Comment by tarilabs** [comment]
TCK meeting 2021-06-10 will check the https://github.com/dmn-tck/tck/issues/386#issuecomment-841774082

**Comment by tarilabs** [comment]
I've been checking again `invoke_001` in `0082-feel-coercion` following DMNv1.3 introductions which Octavian mentions in this https://github.com/dmn-tck/tck/issues/386#issuecomment-752158556 :

https://github.com/dmn-tck/tck/blob/bcd057699507837b9166e9a2b94d7e6296df2289/TestCases/compliance-level-3/0082-feel-coercion/0082-feel-coercion.dmn#L223-L234

which is like writing the FEEL (literal-) expression:

```
bkm_001({name: "foo"})
```

where we can assimilate the BKM "bkm_001" to a function definition such as:

```
function bkm_001( nameAndAge : tNameAndAge) nameAndAge != null
```

Up to here, I think we all agree as valid premises.

Doing the exercise by hand:
1. before implicit conversion, the `{name: "foo"}` does not _conform to_ `tNameAndAge` (missing "age" entry)
2. (checking "after" implicit conversion) from the spec:

> Binding contexts in which the value of an expression is bound to a variable with associated type information (e.g. **binding actual parameters to formal parameters in an invocation**, or binding the result of a decision’s logic to the decsion’s output variable). The expression is subject to conforms to conversion.

meaning:
> When the type of the expression is T1, the target type is T2, and T1 conforms to T2 the value of expression
remains unchanged. Otherwise the result is null.

since we already seen  `{name: "foo"}` does not _conform to_ `tNameAndAge` then this parameter is bound to `null`.

Hence:
```
bkm_001({name: "foo"})
bkm_001(null) // Binding contexts implicit conversion
null != null
false
```

I am happy to discuss if we think now this should be behave differently and what should be suggested differently in the spec, but my understanding of Octavian's introduction of `10.3.2.9.4 Type conversions` chapter in the spec (which is very helpful) was indeed to better formalize this behaviour?

**Comment by StrayAlien** [comment]
Hi @tarilabs, that is the crux of it.  If the above holds true then every (correct arity) function invocation with non-conforming argument passes null in for each _and the function code is executed_.  My thinking is that the text in 10.3.2.13.2 takes precedence:

> If f is not a function, or if the arguments do not conform to the argument list, the result of the invocation is null

In that sense, the result of the invocation is null _and the function code is not executed_.

In @opatrascoiu 's later comment  https://github.com/dmn-tck/tck/issues/386#issuecomment-757454420 it seems that he is also thinking that way (or at least was!).

Perhaps one of those paragraphs needs removing, but, to my mind, the invocation simply resulting in null makes more sense, and will certainly be easier to debug and cuts out the possibility of lots of smaller, harder-to-locate bugs in models.

**Comment by tarilabs** [comment]
Yes I can see the point in about https://github.com/dmn-tck/tck/issues/386#issuecomment-985201115; if the arity/number of parameters matches, it's always like invoking the function with null parameter values.

This however is fine for built-in, user-defined and basically all type of functions.

For example built-in function

```
abs(false)
abs(null) // implicit conversion
null // failing because null is not a number, a days and time duration or a year and month duration (error emitted)
```

For example user-defined function

```
// having somewhere defined:
c1: function(name: string) "Hello, "+name

// invoking it:
c1(47)
c1(null) // implicit conversion
null // failing because string+null is undefined (error emitted)
```

The reason why `invoke_001` in `0082-feel-coercion` was a bit different is that the body of the function actually deals with the null value.

Personally, I don't like coercion in general; however, when the `10.3.2.9.4 Type conversions` was introduced in DMNv1.3 was fine by me since it didn't change the behaviour anyway, eg: even if invoked with null parameters, the observed behaviour is of `null` return and error reported anyway for the reason above. I'm just a bit suprised this github issue seems to backpedal on what was purposefully introduced in DMNv1.3: it is fine by me if there are reasons now to further amend it, as long as we correctly motivate it and follow-up at the OMG's RTF about it.

**Comment by opatrascoiu** [comment]
In my view the conformsTo conversion is not an implicit conversion. Implicit conversions do not loose data (e.g. widening conversions), this one does. This is a conversion that is applied when errors occur (e.g. a decision produces a string and the expected value is number). Unfortunately, the paragraph mentioned above does not clearly specify which conversion is implicit, hence its easy to assume that all the conversions in this section are implicit.

I had a proposal in this space, we started the discussion, but we did not finalize it as there was another idea in the same area (partial dates) and we though is better to tackle both to avoid changing the section twice. Unfortunately, the partial dates idea was never finalized. I am thinking  about discussing it. 

https://issues.omg.org/browse/DMN14-54 has a proposal attached
https://issues.omg.org/browse/DMN14-51 is a duplicate

**Comment by StrayAlien** [comment]
Hi @opatrascoiu - Do those answer the question "is a function invocation with non-conforming arguments short-circuited to result in null,  or do the non-conforming argument(s) coerce to null and the function is invoked as normal".  ?

In the former, the result will always be null. In the latter, the result of the invocation _may or may not_ be null depending on what the function body, and any subsequent logic does.

I'd vote for 'short-circuit' to null as per `10.3.2.13.2`.

**Comment by opatrascoiu** [comment]
@StrayAlien The proposal that I prepared is in line with `10.3.2.13.2`, if the arguments do not conform to the signature  of the function, the function is not invoked and result is null.

**Comment by StrayAlien** [comment]
Thanks @opatrascoiu - reading those issues they seem more about a grammar change than something about invocations.  But, thank you!

To be honest, I'm not even sure I am looking at the correct ticket(s).  I can't see those exact links, but, if I replace 'browse' with 'issues' I do see something.  Like https://issues.omg.org/issues/DMN14-54. Not sure if that is correct.

**Comment by opatrascoiu** [comment]
@StrayAlien The proposal is not about changing the grammar. It's about changing the paragraph about type conversions to make it clear which conversion is implicit and which is not. Also adding the definition of a new implicit conversion that is mentioned informally in other parts of the spec (date to date time conversion). The DMN14-54 has a docx attached to it, it contains a draft of the proposal.

**Comment by StrayAlien** [comment]
Thanks @opatrascoiu - apols, not sure how it happened by I ended up looking at a ticket you raised re a grammar issues creating two parse trees.  maybe too many tabs open.  Thanks again.

**Comment by opatrascoiu** [comment]
Was addressed. Closing.
