### ISSUE TITLE
Type of BKM CreditContingencyFactorTable in 0004-lending.dmn

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#4]
Currently the type is `<variable name="CreditContingencyFactorTable" typeRef="feel:string"/>`

It should be  `<variable name="CreditContingencyFactorTable" typeRef="feel:number"/>` as the output of the decision table is a number.

**Comment by etirelli** [comment]
Submitted PR #18

**Comment by etirelli** [comment]
Fixed.
