### ISSUE TITLE
Students Writing Tests

### ISSUE THREAD

**Issue by agilepro** [dmn-tck/tck#47]
Mihail from MITRE suggested that in his class on DMN modeling, it might be possible to have students write tests that the TCK could use.  It would mean a minimal coordination (what tests are needed at the time).  The Trisotech implementation allows modeling of the decision, as well as testing it.   That would mean the students would need some free access to Trisotech, is that possible?   Denis said that the format on the Trisotech is not exactly the same as TCK, so there is some adjustment that must be made.  It is all one file instead of separate model from input/output.  (Could we get this to automatically produce TCK conforming output?)

This issue is to discuss the possibility, and to understand what we need to do to make this happen.

**Comment by opatrascoiu** [comment]
How about using https://bpmn.io/ to edit the DMN and write tests by hand or using the code generated from the testCases.xsd ?
