### ISSUE TITLE
Unused requirements & params == invalid model?

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#487]
Hi all,

A couple of sentences in the spec have come to mind.  I had unused requirements/params for Decisions and BKMs as compiler warnings, but it seems to me that a model is not valid if Decision and BKM requirements/params are unused.  

Section "7.3.4 InformationItem metamodel":

> A variable representing an instance of Decision or InputData referenced by an InformationRequirement
SHALL be referenced by the value expression of the decision logic in the Decision element that contains the
InformationRequirement element. A parameter in an instance of BusinessKnowledgeModel SHALL be a
variable in the value expression of that BusinessKnowledgeModel element.

"SHALL" in both cases.

Also, "7.1 Introduction":

> each variable associated with the required decisions, required input data, and required knowledge must be referenced in the decision’s expression.

Further in the same section:

> If a business knowledge model element requires one or more other business knowledge models, it must have an explicit
value expression that describes how the required business knowledge models are invoked and their results combined or
otherwise elaborated.

So, this is like a linting check for unused params and requirements.

We have tests both exiting and yet-to-be-merged that fail this.  In practice, people may not feel so strict about it.  But ... it does have more than a few "shalls" and "musts" about it.

Happy for thoughts and comments.

**Comment by tarilabs** [comment]
An easy fix is using the `SHOULD` per RFC jargon and I believe is the most pragmatic suggestion we can ask the RTF to fix.

**Comment by StrayAlien** [comment]
Hi @tarilabs - Thanks.  I didn't mean that actually.  I was thinking from the TCK perspective.  I don't think the spec needs fixing.  A requirement is after all, a _requirement_.  Changing it to 'should" would mean mean it becomes _optional_ ...  and an "optional requirement" doesn't make too much sense.  

Those requirements are part of the documentation that the model represents and (IMO) need to represent the truth.  Having them optional seems to undermine that.  I quite like they are mandatory.   

Actually, I was more meaning we should take it into account into the TCK - and as we're not testing for (and can't test for) model validity, we should consider amending or removing the tests that violate it - and maybe getting an extra validation in or something.  More like that.

And .. as I am the criminal that put in the tests that violate it, I am also happy to unwind them!

**Comment by tarilabs** [comment]
I really believe is a bug in the spec, it should read `SHOULD` wrt to requirements being used in the DRGElement's expression. Otherwise, people using Conformance Level 1 without FEEL could never have a compliant DMN model since they don't specify the decision logic of Decisions/BKMs.

Thank you for bringing this up, we will refer it to the OMG RTF when opening 1.5.

**Comment by StrayAlien** [comment]
hey @tarilabs - good point about level 1 - it is a shame though.  As a mandatory thing it keeps the models 'pure' and kind of enforces them, as documentation, to have only valid requirements.  I kind of like that.

As a thought, if the spec is to change, maybe it should keep those SHALLs and musts but restrict them to level 3 compliance.

**Comment by opatrascoiu** [comment]
Well spotted @StrayAlien ! 

I think the spec should be changed to use `SHOULD` instead of `MUST`. No other known PL or DSL does that, is a proven good language design pattern. There is no point to try and `innovate` when there is no gain. If the requirements are not used the model is still functionally correct.

**Comment by tarilabs** [comment]
Indeed as Octavian reiterates.

Moreover, Editors and Authoring tools can always adopt "tools smarts" to suggest unused requirements, similarly to common IDE suggesting unused variables (say in Java with VSCode underlined with squiggly line)

I've marked this with `for DMNv1.5` label so as soon as new RTF is opened I will raise an OMG JIRA issue, following suggestion in this phase by RTF chairs.

**Comment by tarilabs** [comment]
Reported as https://issues.omg.org/issues/DMN15-88
