### ISSUE TITLE
Node type for Adjudication in 0004-lending-test-01.xml

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#5]
Adjudication is a decision that returns a constant. The associated node in the test case is

		<inputNode name="Adjudication" type="decision">
			<value>ACCEPT</value>
		</inputNode>

In my view an InputNode is associated with TInputDatas and ResultNodes with DRG Elements that produces values 

The associated node should be

		<resultNode name="Adjudication" type="decision">
			<expected>
				<value>ACCEPT</value>
			</expected>
		</resultNode>

This approach will help us catch changes in the definition of constant DRG Elements.

**Comment by etirelli** [comment]
Submitted PR #19

**Comment by etirelli** [comment]
Fixed.
