### ISSUE TITLE
Possible incompatibility issue

### ISSUE THREAD

**Issue by tarsij** [dmn-tck/tck#516]
Hi,

I've been comparing the Drools and Camunda Engines and I run into an incompatibility issue.
When DecisionA depends on DecisionB, and DecisionB has multiple outputs, then Camunda refences the DecisionB outputs by name (e.g. output1, output2), while Drools referenses them as context (DecisionB.output1, DecisionB.output2).
As a result I'm not able to use a Drools DMN file with Camunda.

Here's a link to a sample to show the issue:
https://drive.google.com/file/d/1P4DElcvhybCOEunWJtFzM5zvcpOe2UNw/view?usp=sharing

In the dish decision, the inputs are season.season and guestCount.guestCount (works with Drools).
To make it functional with Camunda, I have to change those to season and guestCount.

Which of these approaches correspond to the standard?

Regards

**Comment by StrayAlien** [comment]
Hi @tarsij - if I understand what you mean, we have quite a few tests that assert that if a decision result is a context, then its values are accessed as <decision>.<fieldname>.  https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0007-date-time/0007-date-time.dmn#L114 is an example.  The decision 'Date' returns a context, and when using it, another decision refers to `Date.<fieldname>`.

Hopefully I understood correctly.

**Comment by tarsij** [comment]
Hi @StrayAlien,

Sorry for the late reply.
I think that's not exactly what I meant.

I'll try to give an example here

```
------------------------------------
|       |       |     DecisionA    |
|-------|-------|------------------|
|  In1  |  In2  |        Out       |
|-------|-------|------------------|

                 ^
                 |
                 |

    ---------------------------
    |      |     DecisionB    |
    |------|------------------|
    |  In  |   Out1  |  Out2  |
    |------|---------|--------|

```

Lets say `In1` will use the `Out1` and `In2` will use the `Out2`.
In Camunda it will be referenced as `Out1` and `Out2` in the input expression.
In Drools it will be referenced as `DecisionB.Ou1` and `DecisionB.Out2.`

**Comment by StrayAlien** [comment]
Hi @tarsij 

Got you.  Though, same still holds.  Both `season` and `guestCount` decisions return contexts - each has a decision table as an expression.  The decision tables both have multiple output columns with a hit policy of `unique`.  The 'type' of a decision table with multiple outputs and a unique hit policy is a context - so therefore accessing the result values of the decision is done using <name>.<field> context syntax.

As far as I can see we don't have an _explicit_ test for this scenario, but, we do have a number of tests where the input expression of a decision table is a referring to a field in a context so uses <name>.<field>, and we also have tests that (directly or indirectly) assert the return type of multi-output decision tables with a unique hit policy is a context. 

I guess, in summary, the way Drools does it is how the TCK test asserts stuff. 

As to why the difference in implementations etc maybe Camunda can chime in? @falko

**Comment by saig0** [comment]
@tarsij your observation is correct. :+1: In Camunda Platform 7, the DMN engine exposes the output of the required decision as an incorrect structure.

The behavior is fixed by the Camunda DMN-Scala extension or the new DMN engine that is used in Camunda Platform 8.
