### ISSUE TITLE
Set Functions

### ISSUE THREAD

**Issue by mankoni** [dmn-tck/tck#525]
Does DMN 1.3 (current) support set functions like say A-B? If I have 2 lists A=[1,2,3,4] and B=[4,5,6], then A-B = [123] and B-A = [5.6]
I need this function to remove some excluded items from a list. Had to resort to a workaround to accomplish this.
This would be similar to Python set fucntions

**Comment by baldimir** [comment]
Hi, there are no set functions like you mention, however there is e.g. list contains function which you can use in combination with a for loop to construct such custom function. Or you can call an external Java function. You can find all list functions in the "10.3.4.4 List functions" section of the specification (https://www.omg.org/spec/DMN/1.3/PDF)

**Comment by mankoni** [comment]
Hi baldimir
  Thx for the quick response. I was able to achieve this with a for loop as you stated - looping through both lists. I faced 2 issues with this approach:
1) When I find a match, I could not use "remove" list function as this requires a "match" to get the offset; Even then , once removed the offset of remaining elements change.
2) the IF then ELSE syntax requires ELSE as mandatory so I had to replace elements that matched with a unique value (say 9999999). I then sorted the resulting array where I get 999999 at the end of the list. These elements need to be removed. Since they are at the end of the list, I counted the # of 999999 and used the sublist function to truncate the list (as opposed to remove function that requires offsets)

This is a workaround but I am not happy with this approach. In the absence of a cleaner approach I will go with this for now.

EXAMPLE: List 1[1,2,3,5,6] ; List 2[3,5]
List1 - List2 = [1,2,6]

Steps:
Find List1 , List2 matching elements and replace with 999999(or some high value) and sort. Output>> [1,2,6,99999,99999]
Count the # of 999999 using for loop using context variable. Output>>2
Use sublist to truncate List 1. sublist(List1,1,count(List1)-2). Output>>[1,2,6]

**Comment by opatrascoiu** [comment]
@mankoni You can raise a DMN issue and propose the functions here https://issues.omg.org/issues/create-new-issue

The issue will be addressed by the DMN  RTF force.

**Comment by mankoni** [comment]
@opatrascoiu , Will do. Thx

**Comment by baldimir** [comment]
@mankoni I played with this a bit and found out you can do something like that with filtering: 

`intersection : function(list1: list, list2: list) (for i in list1 return i)[list contains(list2, item)]`

**Comment by baldimir** [comment]
@mankoni I played with this a bit and found out you can do something like that with filtering:

`intersection : function( list1: list, list2: list ) (for i in list1 return i)[list contains(list2, item)]`

**Comment by brsilver** [comment]
Maybe someone has answered this already.  First of all, lists in DMN are ordered and may contain duplicates.  The distinct values() function removes dups and possibly (not sure) creates an unordered list.  So what you write as A – B could be written as distinct values(A)[not(list contains(distinct values(B), item))].  The variable “item” stands for a member of a list.  So this says filter distinct values(A) with the condition that an item is not contained in the set distinct values(B).







  

More like this in DMN Method and Style book.

 

Bruce Silver

Principal, methodandstyle.com

***@***.***

 

 

 

From: mankoni ***@***.***> 
Sent: Sunday, November 6, 2022 2:18 AM
To: dmn-tck/tck ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dmn-tck/tck] Set Functions (Issue #525)

 

Does DMN 1.3 (current) support set functions like say A-B? If I have 2 lists A=[1,2,3,4] and B=[4,5,6], then A-B = [123] and B-A = [5.6]
I need this function to remove some excluded items from a list. Had to resort to a workaround to accomplish this.
This would be similar to Python set fucntions

**Comment by mankoni** [comment]
Thanks to Bruce and Baldimir. Excellent solutions for my need. I will close this issue
