### ISSUE TITLE
Clarify mixed type workings of `+` operator

### ISSUE THREAD

**Issue by nikku** [dmn-tck/tck#538]
### Describe the context

The [DMN 1.4 specification](https://www.omg.org/spec/DMN/1.4/Beta1/PDF) gives users some pointers on how FEEL should handle invalid inputs and data formats. From what it reads to me the way is `null` cohersion. However there is one case where such cohersion is undesirable: When using the `+` operator to concatenate values of different types to a `string`:

```
// when
str = "I start walking through the park at " + now()
```

### Expected behavior

```
// then (?)
str = "I start walking through the park at 2022-01-10"

// but also (?)
alsoString = 1 + "10"
```

#### Strict type handling + explicit conversion via `string` built-in

```
// string + date cannot be concatenated
str = null

// explicit prior conversion is needed to make this work
str = "I start walking through the park at " + string(now())
```

**Comment by StrayAlien** [comment]
Hi @nikku - this type of functionality (IMO) is intuitive and would be welcome - but, is currently not supported by the spec.  

We have tests to show that <string> + <datetime> (and other stuff) would be null. Around https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0100-arithmetic/0100-arithmetic.dmn#L5610

This is how table 57 `Specific semantics of addition and subtraction` defines it.  

Perhaps this could be the subject of a JIRA to the RTF?  In essence, it is a type coercion to string, but only in certain circumstances - though, the circumstances might be tricky to nail down.

**Comment by nikku** [comment]
Thanks for clarifying. 

I'm closing this issue and will try to figure out how to open a JIRA ticket with the RTF.
