### ISSUE TITLE
Doubtful typing on overloaded built-in function in test

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#560]
I believe a recent change to typings on the lambda tests is not correct, or certainly needs some deeper discussion.

https://github.com/dmn-tck/tck/blob/master/TestCases/compliance-level-3/0092-feel-lambda/0092-feel-lambda.dmn#L512

test decision_015_1 in 0092-feel-lambda.

In the initial PR the `sum` function was passed to a 2 param BKM as both arguments like `bkm_015_1(sum, sum)`.  In the BKM the function was invoked using both its overloaded forms.  The point here is that an overloaded builtin function can be passed as an argument. But, the actual function signature used for `sum` cannot be known until the actual 'call point'.  Until that time, it is not possible to determine the type signature of the `sum` function.  IMO, built in functions operate in a 'grey' area where typing them is not possible in isolation. 

In the original PR, the params of the BKM were untyped for this reason.

The recent change introduced typings on the BKM params but I don't feel this is possible.  If anything, the test as it is now should return `null` as it is not possible for `sum` to satisfy either param types when the function is invoked.

In this modified test we're saying that a function can actually have two type signatures simultaneously - which I don't think is possible.  It can only have one type signature.  The vagueness of the FEEL type system does not handle typing of overloaded built-ins - and the spec gives no indication that a function can simultaneously have two types.  It can be _invoked_ in different ways, sure, but the type is not known is isolation.

I propose we revert the change to this test and leave it as untyped - the test is then valid and asserts the original intention.  Also, subject to discussion we perhaps add the typed version as a new test that returns null to assert that overloaded built-ins are un-typeable until their call-point.  If it needs to go to the RTF, then I suggest we comment out the test.

cc @opatrascoiu

**Comment by baldimir** [comment]
Test commented out. https://github.com/dmn-tck/tck/commit/718c2b73ba4c8e367115af9920bd9f16ef105eea
