### ISSUE TITLE
Day Time Duration division

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#6]
0007-date-time.dmn contains a literal expression
```
                 <literalExpression>
			<text>dtDuration2 / oneHour</text>
		</literalExpression>
```
where both operands are typeRef="feel:dayTimeDuration"

I believe this is not supported in DMN 1.1. (see Table 47: Specific semantics of multiplication and division [)](http://www.omg.org/spec/DMN/1.1/) 

I think we should replace the literal expression with
```
                 <literalExpression>
			<text>dtDuration2.hours</text>
		</literalExpression>
```
and test the "hours" member.

**Comment by brsilver** [comment]
I agree dividing a duration by a duration is omitted from the spec, but I think inadvertent admission.  Proposed solution of using hours property is incorrect; it just extracts the hours component, an integer.  We should move this test to the "non-compliant tests" section of test cases.

**Comment by brsilver** [comment]
We will propose fix to the omission in RTF.

**Comment by etirelli** [comment]
Submitted PR #20

**Comment by etirelli** [comment]
Fixed.
