### ISSUE TITLE
Confused about decision service encapsulatedDecisions - ambiguous - is ch11 example correct?

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#611]
Hi all.  I'm a bit confused about exactly what should be in the encapsulatedDecisions array in a decision service.  The spec seems pretty clear that it is ALL decisions encapsulated in the shape.  And it is all decisions that are evaluated by the decision service.  

6.2.5 Decision service

> The border SHALL enclose all the encapsulated decisions,

> If the set of output decisions is smaller than the set of encapsulated decisions, the Decision Service SHALL be divided into two parts with a straight solid line. One part SHALL enclose only the output decisions and the Decision Service's Name; the other part SHALL enclose all the encapsulated decisions which are not in the set of output decisions.

The above suggests that the encapsulatedDecisions is the _entire_ set of decision inside the decision service shape and the output decisions may be a subset thereof.  Some may be above the line, some below.  Like "SHALL enclose all the encapsulated decisions _which are not in the set of output decisions_" suggests those below the line are a _subset_ of the encapsulatedDecisions. That seems fairly clear to me.

But, then "6.3.10 Decision service metamodel" suggests that the output decisions and encapsulatedDecisions are disjoint sets by specifying one as having min one value, and the other as having min zero values.:

> A DecisionService element has **one or more** associated outputDecisions ... 

.. so it MUST have an output decision ... but then ....

> A DecisionService element has _**zero or more**_ encapsulatedDecisions, which are the instances of Decision required to be encapsulated by this DecisionService, i.e., the Decisions to be evaluated by the Decision Service when it is called.

.. so encapsulatedDecisions could be empty ... but ... represents "Decisions to be evaluated by the Decision Service" - which IMO must include the output decisions - they are evaluated by the DS.

The chapter 11 example has output decisions and encapsulated decisions as disjoint sets, but, the spec on one hand suggests output decisions is a subset of encapsulated decision, yet, in another suggests they are disjoint.

What is correct?  If they are disjoint, then the spec really should be clear about it.  If they are not, then ch11 is incorrect (plus one TCK test)

Apart from ch11 example, this is not covered very well in the TCK.  Hoping for a quick response on this if I may.  Many thanks.

cc @opatrascoiu @tarilabs @baldimir

**Comment by tarilabs** [comment]
Hi @StrayAlien fwiw I've always intended to be disjoint.

I believe the confusion might be the conflation of the term "encapsulated decisions" used to describe what is ~captured by the decision service boundary, and the `encapsulatedDecisions` which is actually a metamodel attribute.

btw the spec also says:

> The requirement subgraph of a DecisionService element is the directed graph composed of the DecisionService element itself and the union of the requirement subgraphs of all the Decision elements that are referenced by its encapsulatedDecisions and outputDecisions.

If they were _not_ disjoint, it would have sufficed to say `encaspulatedDecisions` (without mentioning `outputDecisions`).

Hope this helps

**Comment by StrayAlien** [comment]
hey @tarilabs - nice to hear from you.  I hope you're doing well there.  Phew, okay.  Yes, I think that bit nails it.  Thank you.  

Yes, the term 'encapsulated' suggests the decision service (shape) boundary enclosing things.  I have to say, I must have read it all 30 times and still came away wondering.  The 'union' thing says it.

Thanks again.

**Comment by tarilabs** [comment]
Glad to help 🚀 👍 

If you think there could be an additional paragraph which would clarify, if needed, in the spec, I believe is worthy to raise a ticket once others have also replied, so you could have the broadest picture.
I suggest _adding_ (if needed) only a new paragraph, as changing terminology or the metamodel would be too difficult at this point.

**Comment by opatrascoiu** [comment]
@StrayAlien We should probably raise an issues, discuss it in the RTF and clarify the spec. The main questions is: are the sets disjoint or not.

**Comment by StrayAlien** [comment]
Thanks @opatrascoiu, @tarilabs quoted reference looks pretty concrete.  According to that, they are disjoint, but certainly the use of 'encapsulated' is misleading.  Especially with regards with the decisions 'encapsulated' within the decision service diagram overlay.

I guess maybe, again as suggest by tarilabs, we could consider some wording to assist in understanding the relationship between the DS arrays.

Agree, only the inputs and outputs are needed for execution, but, from a UI perspective, a full understanding of what-goes-where is needed to create a valid model.
