### ISSUE TITLE
Goldman Sachs results for September

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#64]
All the tests are displayed as SKIPPED at [https://dmn-tck.github.io/tck/](https://dmn-tck.github.io/tck/) although the status is SUCCESS.

Looks like a file separator \ vs / issue. Edson could you advise?

**Comment by etirelli** [comment]
@opatrascoiu looking into it

**Comment by etirelli** [comment]
@opatrascoiu you are correct, the results file was using \ instead of / .
I fixed manually. Did you use the runner here from the TCK to generate this or your own runner?

Take a look and let me know if you find any other issue.

**Comment by opatrascoiu** [comment]
I wrote a runner that inherits from the TCK runner.

I'll commit a change to avoid this kind of issue in the future.
