### ISSUE TITLE
Question to test case `decision_015` in `0084-feel-for-loops.dmn`

### ISSUE THREAD

**Issue by dsntk** [dmn-tck/tck#645]
Hi all,

I just wanted to ask/clarify if the test case with `decision_015` in `compliance-level-3/0084-feel-for-loops.dmn` is correct.

The [`decision_015`](https://github.com/dmn-tck/tck/blob/533ddcbb9fa2992de3f191072c79c9c7a53e9249/TestCases/compliance-level-3/0084-feel-for-loops/0084-feel-for-loops.dmn#L92-L98) looks like this:
```xml
<decision name="decision_015" id="_decision_015">
    <variable name="decision_015"/>
    <literalExpression>
        <text>for x in [ [1,2], [3,4] ], y in x return y</text>
    </literalExpression>
</decision>
```
and the [expected result](https://github.com/dmn-tck/tck/blob/533ddcbb9fa2992de3f191072c79c9c7a53e9249/TestCases/compliance-level-3/0084-feel-for-loops/0084-feel-for-loops-test-01.xml#L159-L172) looks like this:

```xml
<testCase id="decision_015">
    <description>for loop with second iterator depending on first iterator</description>
    <resultNode name="decision_015" type="decision">
        <expected>
            <list>
                <item><value xsi:type="xsd:decimal">1</value></item>
                <item><value xsi:type="xsd:decimal">2</value></item>
                <item><value xsi:type="xsd:decimal">3</value></item>
                <item><value xsi:type="xsd:decimal">4</value></item>
            </list>
        </expected>
    </resultNode>
</testCase>
```
So it is expected that the evaluation of the **for** loop `for x in [[1,2],[3,4]], y in x return y`
should give `[1,2,3,4]` as a result.

Do I interpret this correctly saying that the expected result should be **`[[1,2],[3,4]]`**?

Thanks in advance for any help clarifying this case.

**Comment by SimonRinguette** [comment]
Decision 015  result is `[1,2,3,4]`

Decision 016 result in `[[1,2],[3,4]]`
