### ISSUE TITLE
Quesion to test case `nested009` in `1146-feel-context-put-function.dmn`

### ISSUE THREAD

**Issue by dsntk** [dmn-tck/tck#646]
Hi all,

The decision [`nested009`](https://github.com/dmn-tck/tck/blob/533ddcbb9fa2992de3f191072c79c9c7a53e9249/TestCases/compliance-level-3/1146-feel-context-put-function/1146-feel-context-put-function.dmn#L236-L242) looks like this:
```xml
<decision name="nested009" id="_nested009">
    <variable name="nested009"/>
    <literalExpression>
        <text>context put({x:1, y: {a: 0}}, ["y", "a", "b", "c"], 2)</text>
    </literalExpression>
</decision>
```
and the [expected result](https://github.com/dmn-tck/tck/blob/533ddcbb9fa2992de3f191072c79c9c7a53e9249/TestCases/compliance-level-3/1146-feel-context-put-function/1146-feel-context-put-function-test-01.xml#L342C1-L350) like this:
```xml
<testCase id="nested009">
    <description>named params - array value for 'key' gives null</description>
    <resultNode errorResult="true" name="nested009" type="decision">
        <expected>
            <value xsi:nil="true"/>
        </expected>
    </resultNode>
</testCase>
```
but the `context put` function has positional arguments provided and gives non null result like:
**`{x:1, y: {a: {b: {c: 2}}}}`**

Am I missing something?

Thanks in advance for any help in clarifying this.

**Comment by StrayAlien** [comment]
heya - the `context put(context, keys, value)` function is defined as a kind of recursive call back to `context put(context, key, value)`.  That function must have a context object as the first argument.

In the above test, `a` has a value of `0` (zero) and it not a context so, in effect, the call is invalid - hence the null result noting an error condition of some sort. 

From my reading `context put` operates to amend an existing context object, not create them.

**Comment by dsntk** [comment]
Now it's clear, thanks a lot for your help!
