### ISSUE TITLE
Is `[100] = 100` false or null?

### ISSUE THREAD

**Issue by StrayAlien** [dmn-tck/tck#664]
as above.

**Comment by baldimir** [comment]
I think it should be true. There is the coercion defined in the spec. Single item list gets coerced to a single item and vice versa. It is in the section "10.3.2.9.4 Type conversions".

**Comment by StrayAlien** [comment]
Hey Tibor,

I hope you're well there.

It can't be true IMO. The implicit conversions do not cover comparison
operations.

Given that, the logic behind the question is that, intuitively you might
expect it to be false, but, I think the real answer is null. As a
comparison between a list and a primitive is not a valid comparison.

I asked because we have a commented out test.

Greg.

**Comment by opatrascoiu** [comment]
I agree with @StrayAlien on this: the implicit conversions are not applied in the context of comparison.

**Comment by baldimir** [comment]
Agree, it should be null. Discussed this on the meeting with Octavian and Simon.
