### ISSUE TITLE
Issue in the 0068-feel-equality test?

### ISSUE THREAD

**Issue by jvinis** [dmn-tck/tck#682]
The description declares "...expects result: 'true (boolean)'", 
but the allowed answer is false! <allowedAnswers>false (boolean)</allowedAnswers>

<decision name="datetime_008" id="_datetime_008">
        <description>Tests FEEL expression: 'date and time("2018-10-08T00:00:00+01:00") = date and time("2018-10-08T00:00:00@Europe/Paris")' and expects result: 'true (boolean)'</description>
        <question>Result of FEEL expression 'date and time("2018-10-08T00:00:00+01:00") = date and time("2018-10-08T00:00:00@Europe/Paris")'?</question>
        <allowedAnswers>false (boolean)</allowedAnswers>
        <variable name="datetime_008"/>
        <literalExpression>
            <text>date and time("2018-10-08T00:00:00+01:00") = date and time("2018-10-08T00:00:00@Europe/Paris")</text>
        </literalExpression>
    </decision>

**Comment by opatrascoiu** [comment]
@jvinis Thank you for raising this. I believe you are referring to the test for decision_008. The comment in the DMN file is out of synch with the expected value in the TCK file. We need a PR to change the comment. Would you be able to do that?

**Comment by jvinis** [comment]
The problem is at the comments (0068-feel-equality.dmn) and at the expected value (0068-feel-equality-test-01.xml).

<testCase id="datetime_008">
        <description>same datetimes, one with offset and the other with zone are equal</description>
        <resultNode name="datetime_008" type="decision">
            <expected>
                <value xsi:type="xsd:boolean">false</value>
            </expected>
        </resultNode>
    </testCase>

**Comment by opatrascoiu** [comment]
@jvinis Yes, you are right, the boolean value specified in the comments (both DMN and TCK file) do not match the expected value (true in comments and false in expected value tag).

However, the test is correct (actual and expected values are the same). The offset of Europe/Paris between the summer transition (end of March) and autumn transition (end of October) is +02:00 not +01:00. 

I can think of two options: 

> change the comments or 
> change the test to reflect the intention stated in the TCK file by using the +02:00 offset.

**Comment by opatrascoiu** [comment]
I created a PR here https://github.com/dmn-tck/tck/pull/683 to address the issue.

**Comment by baldimir** [comment]
PR merged. Thanks for the issue and for the fix.
