### ISSUE TITLE
Test 0070-feel-instance-of

### ISSUE THREAD

**Issue by jvinis** [dmn-tck/tck#687]
The first is: [{a: "a"}] is list<{a: string}>
The second is: list<t_context_013> is list<{a: string, b: string}>
So list<{a: string}> is a subset of list<{a: string, b: string}>
But the test states that the expected answer is false "(list is not an instance of inline list of inline context type)"
But why?

<dmn:decision name="list_019" id="_list_019">
      <dmn:variable name="list_019"/>
      <dmn:literalExpression>
          
          <dmn:text>[{a: "a"}] instance of list&lt;t_context_013&gt;</dmn:text>
      </dmn:literalExpression>
</dmn:decision>

<dmn:itemDefinition name="t_context_013">
        <dmn:itemComponent name="a">
            <dmn:typeRef>string</dmn:typeRef>
        </dmn:itemComponent>
        <dmn:itemComponent name="b">
            <dmn:typeRef>string</dmn:typeRef>
        </dmn:itemComponent>
    </dmn:itemDefinition>

**Comment by opatrascoiu** [comment]
According to `Table 62: Semantics of type-checking`, the condition is true if the `type(list<{a: string}>)` conforms to type `list<{a: string, b: string}>`. 

According to `10.3.2.9.2 Type Conformance` the type `{a: string}` does not conform to `{a: string, b: string}` - it has less members.

**Comment by jvinis** [comment]
You are right @opatrascoiu !
But the description (list is not an instance of inline list of inline context type) is not right!
Something like the Type A isn't an instance of Type B, because it has fewer members, would be more appropriate.

**Comment by opatrascoiu** [comment]
@jvinis If you want you can raise a PR to make the comment more meaningful.
