### ISSUE TITLE
0007-date-time test - decision cTimezone- uses wrong property to access offset information

### ISSUE THREAD

**Issue by DanielThanner** [dmn-tck/tck#69]
There are some issues for test 0007-date-time:

1. The PDF does not match the DMN file: Decision cTimezone of the DMN file is not listed in the PDF. The diagram shows cOffset instead. I think the diagram is valid, but the decision in the DMN file should be renamed to cOffset.

2. The literal expression of decision cTimezone is "Date-Time2.timezone" and the expected type is feel:dayTimeDuration. I think this is a mismatch. The return type of the timezone property is of type feel:string. Therefore the literal expression should be changed to: "Date-Time2.time offset". Since the decision was already renamed to cOffset (see first bullet point), the decision is now consistent.

**Comment by DanielThanner** [comment]
The semantic of properties is defined in table 53 on page 126 of the spec. Type date and time and type time offers both properties time offset and timezone (last column in table). Since 2 properties are offered, it is obvious that there is a difference between these 2 ones. They should return different information: The timezone property should return the String identifying the zone (for example "Europe/Paris"). The time offset property thould return the time offset of the value (at a specific date) in hours and minutes.

Datatype of timezone property:
Quote of page 131 in the spec: "time string .... followed by a string value that is a time zone identifier..."

Datatype of time offset property:
Time offset is a duration with a max. value in an hour range. Therefore I think it is clear that the return type of the time offset property is a days and time duration (as already used in the DMN TCK testcase).

Nevertheless return types are not explicitly specified in the spec. I have created an issue at OMG: http://issues.omg.org/browse/INBOX-546 for this

**Comment by etirelli** [comment]
As discussed during our last call on Friday, here is what I did:

1. removed the test from Oct/2017 results: https://github.com/dmn-tck/tck/commit/a74fe85ed9b7ff5be049999134e37b183fa0e375

2. submitted a PR to fix the test as per the discussion on this ticket: https://github.com/dmn-tck/tck/pull/71

Once the PR is approved, we can merge it and close this ticket.

**Comment by etirelli** [comment]
Done.
