### ISSUE TITLE
CL3 1110-feel-contains contains an explicit reference to type null

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#83]
AFAIK the DMN standard does not support the feel:null notation. See table 41, page 120 in the DMN 1.1. spec for a list of all the kind / datatypes.

It supports a null literal to define missing values, and an internal type null, compatible with all other types. But this type is internal and is not allowed for the user to use it.

I think 

```
  <dmn:itemDefinition id="_JIz9cLpMEeeHcLDylYgVNA" name="tfeel-contains-function_1_Result">
    <dmn:typeRef>feel:null</dmn:typeRef>
  </dmn:itemDefinition>

```
should be replaced  with 

```
  <dmn:itemDefinition id="_JIz9cLpMEeeHcLDylYgVNA" name="tfeel-contains-function_1_Result">
    <dmn:typeRef>feel:boolean</dmn:typeRef>
  </dmn:itemDefinition>

```
After all, the result of contains is 3-value boolean (true, false and null).
 
Am I missing something?

**Comment by opatrascoiu** [comment]
On the same topic. The DMN 1.1. standard does not specify the behaviour of contains when one argument or both are null (see Table 60 page 133). 

However in our test cases we have

contains(null, null),  contains(null,"bar"), contains("bar", null) expected to return null.

If such behaviour is not specified in DMN 1.1. or to be published in DMN 1.2. we should not have test cases without discussing them with DMN RTF.

Am I missing something?

**Comment by etirelli** [comment]
@opatrascoiu regarding your first comment above, you are correct. Would you mind submitting a PR to fix it?

Regarding the second comment, it falls into the broad range of cases of functions called with invalid parameters. They should return null as per the spec and report an error. As we start introducing tests for error cases, this kind of scenario will show up more and more.

**Comment by opatrascoiu** [comment]
@etirelli just created PR to fix type.

**Comment by etirelli** [comment]
Merged.
