### ISSUE TITLE
Request for Proposal for testing functions

### ISSUE THREAD

**Issue by agilepro** [dmn-tck/tck#89]
Bruce and Simon raised the issue that it is impossible to test a function by itself.  Currently you have to create a model that uses the function, and pass input and output to the model.  It is not impossible to test functions, but it is cumbersome.

They request that the schema for the test be extended to allow the specification of a specific function, as well as the normal input and expected output.

This extensions would then be possible to write a runner that would take the inputs, pass them directly to the function, and compare the output.  We don't have any guarantee that a particular implementation would support the ability to call a function outside of a model.  However, it seems likely that any given implementation would be able to accommodate this.  Whether we use the capability within the TCK is a question we might have to grapple with, but this request comes from those who want to continue to use the TCK Test Format for things beyond what the TCK is directly involved in.

We presume that the schema change would be small, and so making that extension now might enable a lot of future value at very low cost today.

**Comment by SimonRinguette** [comment]
I have created a PR with my proposal... I have documented it in the PR.

https://github.com/dmn-tck/tck/pull/105

**Comment by opatrascoiu** [comment]
What is the meaning of new attribute? The name of the BKM? That means we still have to define the BKM in a dmn file, right? How are we going to test function calls with incorrect signature parameters (e.g. less arguments)? A new BKM ? 

Looks like we have to refactor TestCase, and create a hierachy.

How about we create a new flavor of TestCase, called FEELTestCase that has:
- a<feelExpression> populated with FEEL expressions with no variables
- no <inputNode>s.  
- one <resultNode>

We should probably rename the existing TestCase to DMNTestCase or something similar. It should be used for testing DMN features (e.g. decision tables with UNIQUE hit policy).

We probably should not mix TestCases for DRGElement and FEELExpressions in the same TestCases container.

I am just trying to reduce the amount of XML we write for tests. Having one decision per test case is not great. 

Should be quite easy for all the providers to wrap the FEEL expression into an Decision/BKM with the body a literal expression.

**Comment by opatrascoiu** [comment]
I've tried the approach mentioned above. The tests for functions look like this:

```
<testCases xmlns="http://www.omg.org/spec/DMN/20160719/testcase" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="">
    <labels>
          ...
    </labels>
    <testCase id="001">
        <feelExpression>decimal(1/3, 2)</feelExpression>
        <resultNode type="feel-expression">
            <expected>
                <value xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:decimal">0.33</value>
            </expected>
        </resultNode>
    </testCase>
    ....
</testCases>

```
The approach takes us closer to similar test frameworks (e.g. Fitnesse). 

The proposed approach can be implemented in several ways. For example, 
- add a new element named feelExpression in the TestCase type
- make ResultNode.name optional as the name of the definition is redundant
- TestCases.modelName (dmn file name) is already optional, no change required
- extra null test in DmnTCKRunner to build modelURL only when modelName is present.

If we agree on this approach I'll create a pull request.

**Comment by agilepro** [comment]
Discussed in meeting, Dec 15, and determined we should go forward after simply verifying with Edson about the purpose of the "type" on result and whether needed or not.

**Comment by agilepro** [comment]
resolved by pull request
