### ISSUE TITLE
Type of FinancialMetrics in 0014-loan-comparison

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#9]
Type of BKM FinancialMetrics is `List<Metric>`. Hence, the loop

```			
<contextEntry>
    <variable name="metricsTable" typeRef="tns:tMetrics"/>
    <literalExpression>
        <text>for i in Bankrates return FinancialMetrics(i,RequestedAmt)</text>
    </literalExpression>
</contextEntry>
```
produces a `List<List<Metric>>` which is incompatible with the type of the contextEntry 

Changing the type of the BKM to `typeRef="tns:tMetric"` should solve the issue.

**Comment by etirelli** [comment]
Submitted PR #23
