### ISSUE TITLE
1115-feel-date-function

### ISSUE THREAD

**Issue by opatrascoiu** [dmn-tck/tck#94]
All the itemDefinitions associated with a decision that results in null do not content a typeRef or itemComponent. Doesn't look right to me. We should add typeRef:date in all of them.

**Comment by DanielThanner** [comment]
As listed in figure 31 on page 64 in the DMN spec, the typeRef Attribute (QName) is optional [0..1]. Therefore the files are not wrong.

But it would be nicer to have the expected type listed.

**Comment by opatrascoiu** [comment]
Yes, it is correct from the syntactic point of view  (xml schema validation). I don't think is fine from the semantic point of view. What is the type of a decision with such a type?   

Most of the syntactic constructions in DMN / FEEL are strongly-typed. However, there a few places where the typing is weak (e.g. FEEL user functions). I raised an issue to RTF a while back.

**Comment by opatrascoiu** [comment]
Raised an issue with the RTF.

**Comment by opatrascoiu** [comment]
Started to work on a OMG RFT proposal http://issues.omg.org/browse/DMN12-216
